-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 28-09-2021 a las 03:14:18
-- Versión del servidor: 10.4.20-MariaDB
-- Versión de PHP: 8.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `spacepc`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `admin`
--

CREATE TABLE `admin` (
  `id` int(11) NOT NULL,
  `usuario` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `admin`
--

INSERT INTO `admin` (`id`, `usuario`, `password`) VALUES
(1, 'admin', '$2y$10$idPnFrHbJgA04B/Ylw5iNeCQXRH7E.GsW98R2qSxX4pLW71fMMTii');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `productos`
--

CREATE TABLE `productos` (
  `id` int(11) NOT NULL,
  `nombreP` varchar(100) NOT NULL,
  `marcaP` varchar(100) NOT NULL,
  `descripcionP` varchar(1000) NOT NULL,
  `descripcionP1` varchar(1000) NOT NULL,
  `descripcionP2` varchar(1000) NOT NULL,
  `descripcionP3` varchar(1000) NOT NULL,
  `imagenP` varchar(1000) NOT NULL,
  `precioP` decimal(7,2) NOT NULL,
  `existenciaP` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `productos`
--

INSERT INTO `productos` (`id`, `nombreP`, `marcaP`, `descripcionP`, `descripcionP1`, `descripcionP2`, `descripcionP3`, `imagenP`, `precioP`, `existenciaP`) VALUES
(1, 'G502 HERO', 'logitech', 'Mouse para juegos de alto desempeño G502 HERO.', 'HERO 25K es nuestro sensor para juegos con una precisión de próxima generación y una arquitectura específica. Con el procesamiento de frecuencia de cuadro más rápido hasta la fecha, HERO es capaz de más de 400 ips y 100 - 25.600 dpi, sin suavizado, filtrado ni aceleración. HERO 25K ofrece precisión al más alto nivel competitivo y máxima uniformidad de respuesta. Asegúrate de personalizar y ajustar tu configuración de dpi con Logitech G HUB.', 'Usa Logitech G HUB para programar 11 botones con tus macros y comandos favoritos. Construye, agáchate, lucha cuerpo a cuerpo, sana... pon tus poderes al alcance de tus dedos. Guarda perfiles listos para jugar directamente en el ratón para llevarte tu configuración a cualquier parte.', 'Ajusta el tacto y el deslizamiento del mouse a tu favor. G502 HERO incluye cinco pesas de 3,6 g que se pueden usar en diversas configuraciones de peso frontal, posterior, izquierdo, derecho y central. Experimenta con la alineación y el equilibrio para encontrar el punto ideal para optimizar el desempeño de tu juego.', '1626764245_g502-hero-gallery-1-nb.webp', '405.50', 10),
(2, 'G305', 'logitech', 'Mouse inalámbrico g305 lightspeed para juegos', 'HERO es un nuevo y revolucionario sensor óptico diseñado por Logitech G para ofrecer un desempeño excelente y una eficiencia energética hasta 10 veces superior (en comparación con la generación anterior). El sensor HERO ofrece un desempeño excepcionalmente preciso y estable sin filtros, suavizado ni redondeo de píxeles en el rango de 200 a 12.000 dpi. G305 puede guardar en la memoria integrada hasta 5 perfiles con hasta 5 niveles de dpi cada uno.', 'Mediante ingeniería y diseño integrales, Logitech G desarrolló una robusta solución inalámbrica para afrontar problemas básicos de latencia, estabilidad y conectividad. El resultado final es LIGHTSPEED, una solución inalámbrica de calidad profesional que ofrece un desempeño similar al de la tecnología con cable.', 'El sensor HERO y la tecnología inalámbrica LIGHTSPEED ofrecen una eficiencia extrema para que puedas jugar durante meses. Permite hasta 250 horas de uso con una sola batería AA. Se puede ajustar para que dure hasta 9 meses con un uso estándar en modo de desempeño, que se puede seleccionar a través de Logitech Gaming Software.', '1626764597_g305-lilac-gallery-1.webp', '340.00', 5),
(3, 'G502 HERO k/DA', 'logitech', 'Mouse para juegos de alto desempeño G502 HERO.', 'HERO 25K es nuestro sensor para juegos con una precisión de próxima generación y una arquitectura específica. Con el procesamiento de frecuencia de cuadro más rápido hasta la fecha, HERO es capaz de más de 400 ips y 100 - 25.600 dpi, sin suavizado, filtrado ni aceleración. HERO 25K ofrece precisión al más alto nivel competitivo y máxima uniformidad de respuesta. Asegúrate de personalizar y ajustar tu configuración de dpi con Logitech G HUB.', 'Usa Logitech G HUB para programar 11 botones con tus macros y comandos favoritos. Construye, agáchate, lucha cuerpo a cuerpo, sana... pon tus poderes al alcance de tus dedos. Guarda perfiles listos para jugar directamente en el ratón para llevarte tu configuración a cualquier parte.', 'Ajusta el tacto y el deslizamiento del mouse a tu favor. G502 HERO incluye cinco pesas de 3,6 g que se pueden usar en diversas configuraciones de peso frontal, posterior, izquierdo, derecho y central. Experimenta con la alineación y el equilibrio para encontrar el punto ideal para optimizar el desempeño de tu juego.', '1626764544_g502-hero-kda-gallery-01.webp', '499.00', 10),
(4, 'G305 K/DA', 'logitech', 'Mouse inalámbrico G305 lightspeed para juegos.', 'HERO es un nuevo y revolucionario sensor óptico diseñado por Logitech G para ofrecer un desempeño excelente y una eficiencia energética hasta 10 veces superior (en comparación con la generación anterior). El sensor HERO ofrece un desempeño excepcionalmente preciso y estable sin filtros, suavizado ni redondeo de píxeles en el rango de 200 a 12.000 dpi. G305 puede guardar en la memoria integrada hasta 5 perfiles con hasta 5 niveles de dpi cada uno.', 'Mediante ingeniería y diseño integrales, Logitech G desarrolló una robusta solución inalámbrica para afrontar problemas básicos de latencia, estabilidad y conectividad. El resultado final es LIGHTSPEED, una solución inalámbrica de calidad profesional que ofrece un desempeño similar al de la tecnología con cable.', 'El sensor HERO y la tecnología inalámbrica LIGHTSPEED ofrecen una eficiencia extrema para que puedas jugar durante meses. Permite hasta 250 horas de uso con una sola batería AA. Se puede ajustar para que dure hasta 9 meses con un uso estándar en modo de desempeño, que se puede seleccionar a través de Logitech Gaming Software.', '1626764761_g304-kda-gallery-1.webp', '360.00', 10),
(5, 'PRO X', 'logitech', 'PRO X superlight.', 'Uno de los resultados de nuestra colaboración constante con los mejores profesionales de esports, PRO X SUPERLIGHT está pensado con un solo objetivo: crear el mouse inalámbrico para juegos PRO más ligero posible sin renunciar a la calidad, la integridad estructural ni los estándares profesionales ofrecidos por Logitech G. Gana el juego antes que nadie.', 'Nuestro mouse PRO más ligero hasta la fecha, PRO X SUPERLIGHT, supone un avance de ingeniería con un peso inferior a 63 gramos (casi un 25% más ligero que nuestro mouse inalámbrico PRO estándar). Este logro se debe a una meticulosa labor para producir una máxima reducción de peso sin comprometer el desempeño.', 'El sensor HERO 25K exclusivo de Logitech G proporciona una precisión, velocidad y homogeneidad inigualables. PRO X SUPERLIGHT ofrece máxima exactitud y control riguroso, para actuar con toda confianza, especialmente en los momentos más intensos de un torneo.', '1626764839_pro-x-superlight-black-gallery-1.webp', '1200.00', 5),
(6, 'G203', 'logitech', 'G203 lightsync.', 'Te proporciona un seguimiento preciso del cursor y una respuesta rápida. Con una sensibilidad ajustable de 200-8.000 dpi, puedes elegir el valor idóneo para tu estilo de juego. Utiliza el software Logitech G HUB para programar hasta 5 preajustes.', 'El diseño clásico de seis botones te da confort y confianza para que puedas explorar, lanzar hechizos y jugar como quieras. Utiliza el software Logitech G HUB para asignar a los botones comandos en el juego, controles del sistema o enlaces de teclas con los que simplificar tus acciones.', 'Los botones izquierdo y derecho primarios tienen el exclusivo sistema de tensión de botones con resortes metálicos Logitech G, que ofrece una actuación precisa de los botones y una experiencia uniforme constante.', '1626765265_g203-blue-gallery-1.webp', '270.00', 5),
(7, 'G703', 'logitech', 'Mouse inalámbrico G703 lightspeed para juegos con sensor hero.', 'G703 LIGHTSPEED entra en la próxima generación de desempeño con el sensor avanzado HERO 25K. Prepárate para el seguimiento de próximo nivel, tecnología LIGHTSPEED mejorada y una eficiencia energética 10 veces superior a la de la generación anterior. Añade POWERPLAY para no tener que preocuparte nunca más por cargar y completa el equipamiento con la tecnología LIGHTSPEED más avanzada.', 'G703 combina confort, durabilidad y desempeño supremos con un diseño confortable y recubrimiento lateral de goma para control. Personaliza tu experiencia de juego con una pesa de 10 g opcional y seis botones programables.', 'El avanzado sistema de tensión de botones con resortes metálicos mantiene los botones izquierdo y derecho primarios listos para accionarse con menos esfuerzo. Eso aporta una sensación, respuesta y consistencia de botones excepcionales cada vez que se hace click.', '1626765376_g703-gallery-1.webp', '720.00', 10),
(8, 'G903', 'logitech', 'Mouse inalámbrico G903 lightspeed para juegos con sensor hero.', 'Cada componente de G903 se ha optimizado para reducir el peso y mantener la robustez, desde moldeo de paredes finas hasta el diseño del botón rueda hiperrápido hueco \"con rayos\". El resultado es un mouse inalámbrico repleto de funciones que pesa sólo 110 gramos. Disfruta de total confort durante usos prolongados y siente la rapidez de respuesta al movimiento.', 'El mouse G903 está equipado con el sensor óptico PMW3366, sin filtros, suavizado ni aceleración en toda la gama de dpi (200-12.000 dpi) y ofrece un seguimiento de precisión excepcional y una respuesta constante a cualquier velocidad. Para obtener precisión y velocidad aún mejores, puedes optimizar el sensor según tu superficie de juego usando los ajustes de superficie de Logitech Gaming Software.', 'G903 tiene una exclusiva tecnología de ajuste de reloj que reduce significativamente el consumo de energía del sensor, para que puedas jugar sin cesar durante 32 horas con una sola carga. El asistente de batería en Logitech Gaming Software te mantiene informado sobre el nivel de carga y muestra aproximadamente cuánto durará la batería.', '1626765451_g903-gallery-1.webp', '1159.00', 5),
(9, 'G502', 'logitech', 'Mouse inalámbrico G502 lightspeed para juegos.', 'El mouse G502 es todo un icono que ha ocupado las primeras posiciones de las listas generación tras generación. Y es el mouse que eligen quienes juegan en serio. Ahora, el mouse G502 se une a las filas de los mouse inalámbricos para juegos más avanzados del mundo con el lanzamiento de G502 LIGHTSPEED.', 'LIGHTSPEED es una tecnología ultrarrápida y confiable con desempeño probado en competencia por profesionales de eSports. G502 LIGHTSPEED posee además el sensor de próxima generación HERO 25K y es compatible con POWERPLAY. Junto con esta novedosa tecnología avanzada, G502 LIGHTSPEED mantiene esa forma apreciada por todos y logra una reducción de peso de 7 gramos.', 'La tecnología RGB LIGHTSYNC de espectro completo y totalmente personalizable reacciona de manera inteligente a la acción del juego, el audio o el color de la pantalla. Configura todos tus dispositivos y accesorios RGB Logitech G para sincronizarlos juntos.', '1626765534_g502-lightspeed-gallery-1.webp', '770.00', 10),
(10, 'G403', 'logitech', 'Mouse G403 hero para juegos.', 'Te presentamos el sensor HERO 25K de próxima generación, nuestro sensor más avanzado, con seguimiento 1:1, 400+ IPS y una sensibilidad máxima de 100-25.600 dpi. Y además, sin suavizado, aceleración ni filtros.', 'G403 es ligero, con un diseño confortable, para amoldarse a tu mano y con recubrimiento de goma para mayor control. Una pesa extraíble opcional de 10 g te permite ajustar el peso a tus preferencias.', 'Con un tiempo de respuesta de 1 ms, G403 es hasta 8 veces más rápido que los mouse estándar no diseñados específicamente para juegos. Por eso ofrece clicks y movimientos prácticamente instantáneos. G403 también dispone de un sistema de tensión de botones con resortes metálicos que mantiene los botones izquierdo y derecho primarios listos para accionarse con menos esfuerzo.', '1626765592_g403-prodigy-gaming-mouse15.webp', '435.00', 15),
(11, 'MX518', 'logitech', 'Mouse MX518 para juegos.', 'El renovado MX518 cuenta con las últimas innovaciones en tecnología de juegos, entre ellas nuestro exclusivo sensor HERO 16K. Es el más preciso de nuestros sensores para juegos, con un desempeño de próxima generación y una flamante arquitectura.', 'MX518 es uno de los mouse para juegos más populares de la historia y legiones de aficionados de todo el mundo pidieron a Logitech G que lo sacara de su retiro. Y así lo hicimos. Restauramos meticulosamente todas las piezas originales, incluida la placa pulida.', 'MX518 viene totalmente equipado. Guarda hasta cinco perfiles en la memoria integrada, utilizando el software Logitech G HUB, y llévalos contigo. La configuración guardada funcionará en cualquier PC sin necesidad de software adicional ni de iniciar sesión.', '1626765645_mx518-hero-gallery-1.webp', '359.00', 10),
(12, 'PRO', 'logitech', 'Mouse PRO para juegos.', 'HERO 25K es nuestro sensor para juegos con una precisión de próxima generación y una arquitectura específica. HERO 25K es capaz de 400+ ips y 100 - 25.600 dpi, sin suavizado, filtrado ni aceleración en todo el rango de dpi. HERO 25K ofrece precisión al más alto nivel competitivo y máxima uniformidad de respuesta. Asegúrate de personalizar y ajustar tu configuración de dpi con Logitech G HUB.', 'PRO se inspira en el sencillo y clásico chasis de Logitech G100 y G100s, favorito de destacados profesionales de eSports. La uniformidad y el confort son fundamentales para lograr el máximo. El mouse PRO cumple en ambos casos.', 'El sistema mecánico de tensión de botones del mouse para juegos Logitech G PRO aumenta la coherencia de respuesta de los botones izquierdo y derecho del mouse, y requiere menos esfuerzo de click. Eso contribuye a la gran rapidez y confiabilidad de las acciones de click al más alto nivel de juego competitivo.', '1626765718_plasma-hero-carbon-gallery-4.webp', '700.00', 5),
(13, 'G603', 'logitech', 'Mouse inalámbrico G603 lightspeed para juegos.', 'G603, con el revolucionario sensor HERO y tecnología inalámbrica LIGHTSPEED, ofrece un desempeño excepcionalmente preciso y uniforme, y una impresionante duración de batería que establece un nuevo estándar de juego inalámbrico.', 'La conectividad doble con LIGHTSPEED y Bluetooth® permite conectar y controlar varios dispositivos en diversas plataformas. Alterna fácilmente entre los dos dispositivos conectados con sólo presionar un botón.', 'Mediante ingeniería y diseño integrales, Logitech G desarrolló una robusta solución inalámbrica para afrontar problemas básicos de latencia, estabilidad y conectividad. El resultado final es LIGHTSPEED, una solución inalámbrica de calidad profesional que ofrece un desempeño similar al de la tecnología con cable.', '1626765785_g603-gallery-1.webp', '569.00', 5),
(14, 'G600', 'logitech', 'Mouse para juegos MMO.', 'Todo preconfigurado para uso inmediato en juegos MMO. G600 incluye tres botones principales, 12 botones para el pulgar, un botón rueda presionable e inclinable y un botón G-Alt para doblar las opciones y dominar. Si quieres puedes usar Logitech G HUB para disponer de todas las opciones de programación y personalización.', 'Dispón de acceso inmediato y completo a las 12 habilidades principales de MMO bajo el pulgar. El exclusivo diseño con dos secciones del panel para el pulgar se desarrolló con la aportación directa de jugadores de MMO y de los principales desarrolladores de juegos MMO.', ' BOTÓN G-ALT Usa el botón G-Alt para duplicar el número total de funciones personalizables. En tu configuración predeterminada, al mantener pulsado el botón G-Alt, se activa una segunda función para cada tecla G. O se puede configurar el botón G-Alt para cambiar temporalmente el valor de dpi y obtener precisión de cursor adicional.', '1626765820_g600-gallery-1-nb.webp', '419.00', 10),
(15, 'G203 PRODIGY', 'logitech', 'Mouse G203 para juegos.', 'Las 1.000 señales por segundo de G203 representan una rapidez 8 veces superior a la de los mouse estándar. Por eso al moverlo o hacer click, la respuesta en pantalla es casi instantánea.', 'G203 se inspira en el diseño clásico del legendario mouse Logitech G100S para juegos. Un favorito entre los jugadores de todo el mundo y los profesionales de eSports, tiene un diseño clásico cuya ingeniería hemos remodelado y optimizado íntegramente, para hacerlo ligero, duradero y confortable.', 'El sistema mecánico de tensión de botones utiliza muelles metálicos para mantener los botones izquierdo y derecho siempre a punto para el click, lo que reduce la fuerza requerida para la acción. Combinado con botones izquierdo y derecho individuales, mejora la uniformidad de acción y ofrece una excepcional definición de click y respuesta.', '1626766022_g203-gallery-1.webp', '449.00', 5),
(16, 'G300S', 'logitech', 'Mouse óptico G300S para juegos.', 'La configuración de fábrica ofrece excelentes resultados o puedes configurar activadores para realizar con un solo botón acciones complejas que suelen requerir el uso de menús. Ten a tu alcance las comunicaciones activadas con sólo un botón. Reduce temporalmente el valor de dpi.', 'Diseño versátil en una forma compacta. Este mouse se ha creado para ofrecer confort y duración. La forma equilibrada es adecuada tanto para la mano izquierda como para la derecha.', 'El cambio instantáneo de dpi te permite alternar con un click entre dos valores de sensibilidad con los que podrás pasar de apuntar con precisión de píxel a 250 dpi a rápidos movimientos a 2.500 dpi. Usa LGS para personalizar la configuración de dpi de acuerdo con tu estilo de juego. Además, el ciclo de dpi te permite elegir entre cinco valores durante el juego.', '1626766077_g300s-gallery-1.webp', '259.00', 5),
(17, 'PRO K/DA', 'logitech', 'Teclado PRO.', 'Los interruptores mecánicos avanzados GX con click perceptible se concibieron para el máximo desempeño, respuesta y durabilidad. Poseen un click audible y tienen una protuberancia táctil para ofrecer respuesta.', 'Resalta las teclas importante o simplemente luce con orgullo los colores de tu equipo. Personaliza la iluminación y las animaciones con el software G HUB y guarda diseños de iluminación estática en la memoria integrada para sistemas de torneos.', 'Un diseño sin teclado numérico y un cable extraíble ofrecen más espacio para usar el mouse y facilitan llevarlo en los viajes a torneos por todo el mundo.', '1626766331_g600-gallery-1-nb.webp', '1444.00', 10),
(18, 'G915 TKL', 'logitech', 'Teclado mecánico sin teclado numérico logitech G915 TKL rgb.', 'Un gran avance en diseño e ingeniería, ahora en combinaciones de colores en blanco y negro. G915 TKL incorpora tecnología inalámbrica LIGHTSPEED de calidad profesional, RGB LIGHTSYNC avanzada e interruptores mecánicos de perfil bajo y alto desempeño. Creado meticulosamente con materiales premium, el G915 TKL tiene un sofisticado diseño de incomparable belleza, resistencia y desempeño. Y ahora con un diseño aún más compacto. G915 TKL. Juega en la siguiente dimensión.', 'G915 TKL dispone de las mismas tecnologías avanzadas que G915 (pero en un diseño más compacto, que ofrece más espacio para el movimiento del mouse). El receptor USB se puede guardar en la parte posterior del teclado para facilitar el transporte.', 'El G915 TKL dispone de tecnología inalámbrica LIGHTSPEED de calidad profesional con una vertiginosa rapidez de 1 ms. El G915 TKL también funciona perfectamente conectado mediante USB, lo que permite la carga y el uso simultáneos.', '1626766585_g915-tkl-gallery-1-white.webp', '1840.00', 5),
(19, 'G815', 'logitech', 'Teclado mecánico rgb lightsync G815 para juegos.', 'Tecnologías de juego avanzadas en un sofisticado diseño ultrafino. Totalmente personalizable, equipado con RGB LIGHTSYNC y teclas G específicas. Diseñado para un juego de alto desempeño con interruptores mecánicos GL de perfil bajo en versiones de click perceptible, táctil y lineal. Usa el G815 y juega en la siguiente dimensión.', 'El G815 es una proeza de ingeniería y diseño con una construcción increíblemente refinada y sorprendentemente fina sin merma para el desempeño ni las funciones. Duradero, confortable y preparado para intensas sesiones de juego, el G815 representa la próxima generación de teclados mecánicos para juegos.', 'Conecta y alimenta más dispositivos de forma rápida y práctica. Un cable USB especial adicional conecta el puerto de paso USB en la parte posterior del teclado para la máxima potencia y velocidad de datos. Puedes conectar y cargar un dispositivo o conectar un mouse para cargar contra tu enemigo, sin perderte nada de la acción.', '1626766462_g815-gallery-1.webp', '1616.00', 10),
(20, 'G915', 'logitech', 'Teclado mecánico inalámbrico rgb lightspeed G915 para juegos.', 'Un avance en diseño e ingeniería, el G915 incorpora tecnología LIGHTSPEED inalámbrica de calidad profesional, RGB LIGHTSYNC avanzada y nuevos interruptores mecánicos de alto desempeño y perfil bajo. Construido meticulosamente con materiales de primera calidad, el G915 tiene un sofisticado diseño de incomparable belleza, resistencia y desempeño. Descubre el G915 LIGHTSPEED y juega en la siguiente dimensión.', 'El G915 dispone de tecnología inalámbrica LIGHTSPEED de calidad profesional con una vertiginosa rapidez de 1 ms. Es la tecnología en la que confían profesionales de eSports de todo el mundo para sus torneos. El G915 también funciona perfectamente conectado mediante USB, lo que permite la carga y el uso simultáneos.', 'El G915 es una proeza de ingeniería y diseño. Meticulosamente construido con materiales de primera calidad, el G915 es increíblemente refinado, sorprendentemente fino y hecho ante todo para ofrecer desempeño y funciones. Duradero, confortable y preparado para intensas sesiones de juego, el G915 representa la próxima generación de teclados mecánicos para juegos.', '1626766564_g915-gallery-1.webp', '2003.00', 5),
(21, 'G513 CARBON', 'logitech', 'Teclado mecánico rgb lightsync G513 para juegos.', 'G513 es un teclado para juegos de alto desempeño con interruptores mecánicos avanzados GX Brown Tactile.. El reposamanos extraíble de espuma viscoelástica y la construcción de aleación de aluminio premium complementan las características de G513 para hacerlo el mejor de su clase.', 'La espuma viscoelástica recupera rápidamente su forma original, por lo que cada uso es tan cómodo como al principio. La confortable espuma tiene un recubrimiento de piel sintética suave y duradero, que es impermeable, resistente al sudor y fácil de limpiar. El reposamanos se asienta firmemente sobre seis patas de goma montadas en la base. , listo para jugar.', 'G513 está fabricado con una aleación de aluminio y magnesio 5052, increíblemente robusta y duradera, apta para posibilitar un diseño minimalista y atractivo. La rigidez de la aleación 5052 también proporciona un chasis robusto y antideslizante que alberga un conjunto completo de características para una experiencia de juego inmejorable.', '1626766675_g513-carbon-gallery-1.webp', '1353.00', 5),
(22, 'G100S', 'logitech', 'Combinación G100S para juegos.', 'G100s continúa el legado de los ratones para juegos G1 y G100 integrando optimizaciones del exclusivo sensor Delta Zero para un control de cursor de máxima precisión. Tanto para recorrer la pantalla a toda velocidad como para centrarse en un solo píxel, el sensor de 2500 dpi responde con precisión al movimiento de la mano.', 'Las condiciones de juego son una tortura para un mouse común. Un jugador promedio de League of Legends puede hacer más de 50.000 clicks en cada partida. G100s está diseñado para durar. Los microinterruptores mecánicos primarios mejorados son capaces de hasta 20 millones de clicks.', 'Gracias a la superficie con curvas naturales diseñada para brindarte máxima comodidad, llegarás al final de la competencia sin importar el tamaño de mano o estilo de sujeción que tengas, ni si eres zurdo o diestro. La forma de trapecio invertido te ayuda a sujetar el mouse con firmeza sin tener que pensarlo.', '1626766712_g100s-gaming-keyboard-mouse-combo3.webp', '900.00', 20),
(23, 'G213 PRODIGY', 'logitech', 'Teclado G213 rgb para juegos.', 'El teclado G213 para juegos está dotado de teclas Logitech G Mech-Dome ajustadas especialmente para ofrecer una respuesta táctil superior y un perfil de desempeño global similar al de un teclado mecánico. Las teclas Mech-Dome tienen una altura estándar, ofrecen un recorrido total de 4 mm, una fuerza de actuación de 50 g y un funcionamiento silencioso.', 'G213 tiene cinco zonas de iluminación individuales, cada una de ellas personalizable en una paleta de aproximadamente 16,8 millones de colores y distintos niveles de brillo, a juego con tu estilo personal, el sistema o el entorno. La tecnología LIGHTSYNC proporciona iluminación de próxima generación que sincroniza la iluminación y los perfiles del juego con tu contenido.', 'La membrana y el armazón de teclas de G213 se diseñaron teniendo en cuenta la realidad de uso, por eso ofrece resistencia a salpicaduras probada con hasta 60 ml de líquido. El resultado es un teclado listo para afrontar los avatares del juego diario.', '1626766755_g213-prodigy-gaming-keyboard15.webp', '626.00', 15),
(24, 'G413', 'logitech', 'Teclado mecánico con retroiluminación G413 para juegos.', 'G413 se ha concebido, diseñado y creado para ofrecer desempeño avanzado con las funciones justas. La compacta carcasa es de aleación de aluminio 5052 ligera y altamente resistente. En la base hay un sistema de gestión de cables de mouse y audífonos, y patas ajustables con estabilizadores de goma para la colocación en el ángulo de uso más adecuado.', 'El diseño de Romer-G incluye también iluminación a través de la superficie de las teclas. De este modo las teclas están siempre visibles, algo especialmente importante durante sesiones de juego nocturnas (que son las mejores). Así es como G413 Carbon con retroiluminación roja y G413 Silver con luz blanca logran ese aspecto de alta categoría y concentración.', 'La cubierta superior de aluminio y magnesio 5052 bruñido viene a ser el eje del teclado. El resultado es un atractivo diseño dotado de una completa gama de funciones. Con un acabado y desempeño de gama alta como objetivos, el G413 está hecho con materiales de gran calidad.', '1626766808_g413-gallery-1.webp', '800.00', 5),
(25, 'G333 K/DA', 'logitech', 'Audífonos con micrófono G333 K/DA para juegos.', 'Sumérgete completamente en el juego dondequiera que juegues. G333 K/DA ofrece audio de alta fidelidad y comunicaciones claras en cualquier plataforma, ya sea móvil, de consola o de escritorio. Donde quiera que estés, llega más lejos en el mundo de los juegos.', 'El diseño de G333 K/DA está pensado específicamente para una experiencia de juego óptima. Los transductores específicos, uno para altos/medios y uno para graves, proporcionan audio detallado para recrear el mundo del juego con máxima precisión.', 'El micrófono de calidad integrado en el cable ofrece comunicaciones y chat claros, mientras que los controles integrados te permiten reproducir, pausar y silenciar el audio. El micrófono también te permite contestar llamadas cuando juegues en el celular.', '1626766915_g413-gallery-1.webp', '390.50', 10),
(26, 'G733', 'logitech', 'Audífonos G733 con micrófono inalámbricos lightspeed rgb para juegos.', 'Por fin, unos audífonos que pueden ser tan expresivos como tú. Los audífonos G733 son inalámbricos y se diseñaron pensando en el confort. Y están equipados con todo el sonido envolvente, los filtros de voz y la iluminación avanzada que necesitas para lucir, sonar y jugar con más estilo que nunca.', 'Desde cintas de suspensión reversibles a protectores de micrófono, los audífonos G733 están listos para la personalización con una amplia variedad de coloridos accesorios. Mezcla y combina. Voltea y acopla. Diviértete sin parar con tu elección de accesorios a la venta por separado.', 'Alrededor de 16,8 millones de colores, dos zonas para personalizar la iluminación y hacerla completamente tuya. Elige tus colores, visualiza tu audio, intégrate en tu mundo de juego, o enloquece con las animaciones predefinidas o crea las tuyas propias. Prográmalo todo con el software gratuito para juegos G HUB.', '1626766982_g733-lilac-gallery-1.webp', '1100.00', 5),
(27, 'G733 K/DA', 'logitech', 'Audífonos G733 con micrófono inalámbricos lightspeed rgb para juegos.', 'Por fin, unos audífonos que pueden ser tan expresivos como tú. Los audífonos G733 son inalámbricos y se diseñaron pensando en el confort. Y están equipados con todo el sonido envolvente, los filtros de voz y la iluminación avanzada que necesitas para lucir, sonar y jugar con más estilo que nunca.', 'La tecnología inalámbrica LIGHTSPEED te proporciona más de 29 horas de duración de batería y hasta 20 metros de libertad inalámbrica confiable. Depende del uso y de los dispositivos. La duración de la batería se basa en un volumen de audífonos configurado en 50% y la iluminación desactivada. Juega sin enredarte con un cable. Relájate y sumérgete en el juego, la música, la película, o lo que te apetezca. Sé libre y juega a tu manera.', 'Escúchalo todo con nuestros propios transductores PRO-G diseñados para ofrecer un sonido preciso y de gama completa. Sumérgete en el juego más que nunca con el sonido envolvente de próxima generación DTS Headphone:X 2.0.3Funciones avanzadas como DTS Headphone:X 2.0, Blue VO!CE RGB LIGHTSYNC no están disponibles en PlayStation 4. Suena increíble y nítido, con el micrófono con certificación para Discord.', '1626767027_g733-kda-gallery-1.webp', '1110.00', 10),
(28, 'PRO X PARA JUEGOS', 'logitech', 'PRO X para juegos audífonos inalámbricos con micrófono lightspeed.', 'La tecnología inalámbrica LIGHTSPEED, únicamente de Logitech G, te permite jugar sin cables y sin compromisos en latencia, conectividad o batería. Juega en total libertad con más de 20 horas de batería y un radio de acción de 15 metros utilizando la robusta frecuencia de 2,4 GHz.', 'La tecnología de micrófono BLUE VO!CE te da la opción de elegir filtros de voz en tiempo real. Reduce el ruido, añade compresión y elimina el siseo. Y garantiza además que tu voz suene más rica, limpia y profesional. Obtén comunicaciones de voz dentro del juego personalizables, con calidad de estudio, con BLUE VO!CE a través del software para juegos G HUB.', 'Un diseño elegante, minimalista y profesional creado para durar con horquilla de aluminio y diadema reforzada con acero premium. Las almohadillas y la diadema confortabilísimas de espuma viscoelástica están forradas en piel sintética afelpada y proporcionan aislamiento pasivo de ruido. También se incluyen almohadillas de tejido aterciopelado adicionales para ofrecer una sensación más suave.', '1626767366_pro-wireless-headset-gallery-1.webp', '1600.00', 20),
(29, 'PRO X', 'logitech', 'Audífonos PROX X para juegos con blue vo!Ce.', 'La tecnología de micrófono BLUE VO!CE te ofrece una selección de filtros de voz en tiempo real para reducir el ruido, añadir compresión y eliminar el siseo. Además, garantiza que tu voz suene más rica, limpia y profesional. Consigue comunicaciones de voz en el juego consistentes y con calidad de estudio con BLUE VO!CE a través del software para juegos G HUB.', 'La espuma viscoelástica envuelta en piel sintética premium o tejido aterciopelado transpirable te proporciona confort duradero. Para que puedas jugar más tiempo y más duro, y concentrarte en ganar.', 'Los audífonos PRO-G poseen un diseño exclusivo de malla híbrida para ofrecer una imagen espacial del sonido increíblemente clara y precisa. Podrás oír pisadas y señales ambientales con impresionante claridad y obtendrás la ventaja competitiva que necesitas para ganar. Ahora, con los transductores de 50 mm.', '1626767403_pro-headset-gallery-1.webp', '1030.99', 10),
(30, 'G935', 'logitech', 'Audífonos inalámbricos con micrófono, sonido envolvente 7.1 y lightsync G935 para juegos.', 'Los audífonos G935 ofrecen múltiples ventajas con la posibilidad de elegir entre el uso con cable o inalámbrico. Juega con conexión inalámbrica de 2,4 GHz durante 12 horas por carga sin iluminación u 8 horas con la iluminación predeterminada. Depende del uso y de los dispositivos. La estimación de 12 horas de duración de la batería se basa en un uso sin iluminación LED y volumen de audífonos al 50%. También puedes usar la entrada analógica de 3,5 mm en los audífonos para usar un cable conectado a la consola, el celular o la PC, si prefieres prescindir de baterías.', 'La malla híbrida tejida de los transductores Pro-G de 50 mm contribuye a una mayor plenitud, profundidad y claridad de sonido a cualquier volumen. Con el nuevo diámetro aumentado, Pro-G suena mejor que nunca. Los sonidos de baja frecuencia (como explosiones y complejas bandas sonoras) son aún más completos y cinemáticos.', 'Con el software para juegos Logitech G HUB, puedes personalizar la iluminación RGB LIGHTSYNC, programar teclas G con macros y comandos de juego y adaptar las preferencias de audio con perfiles únicos para cada juego y aplicación.', '1626767441_g935-gallery-1.webp', '1508.99', 10),
(31, 'G533 WIRELESS', 'logitech', 'Audífonos inalámbricos con micrófono G533 con sonido envolvente 7.1 para juegos.', 'Los G533 son unos audífonos con micrófono para juegos de calidad profesional dotados de DTS Headphone:X para sonido envolvente 7.1, transductores Pro-G™ para un audio impactante sin distorsión y 15 horas de duración de la batería para una conexión inalámbrica confiable.', 'G533 refleja con precisión el entorno de juego con sonido envolvente virtual de 7.1 canales. Oye y detecta enemigos, amenazas y todo lo que te rodea. Usa Logitech G HUB para ajustar los niveles de volumen de cada uno de los 7 canales de audio.', 'Oye tus juegos con sonido alto y claro, con la precisión y autenticidad proyectadas por los diseñadores. Los transductores Pro-G producen graves potentes y agudos claros gracias a la malla híbrida que reduce drásticamente la distorsión.', '1626767493_g533-gallery-1.webp', '1150.00', 5),
(32, 'G635', 'logitech', 'Audífonos con micrófono G635 lightsync 7.1 para juegos.', 'Oye enemigos al acecho, pistas de habilidades especiales y todo lo que te rodea. Entra de lleno en el mundo del juego y escucha al detalle las fabulosas pistas de audio. La tecnología de audio más avanzada se combina con materiales de gran resistencia para ofrecer un sonido cinemático expansivo. Los transductores Pro-G™ de 50 mm y el sonido envolvente DTS Headphone:X 2.0', 'El ambiente de juego espacial de alta precisión te permite detectar claramente la posición y la distancia en un espacio sonoro 3D completo. La clara percepción de lo que te rodea puede suponer la diferencia entre la victoria y la derrota.', 'Mic+ de 6 mm es un micrófono de varilla volteable para silenciar, mejorado para comunicaciones increíblemente claras y precisas. La varilla tiene un LED indicador para que sepas si el micrófono está silenciado. Cuando no se use, la varilla puede plegarse contra los audífonos y queda casi invisible, con el micrófono silenciado.', '1626767535_g635-gallery-1-nb.webp', '1198.99', 10),
(33, 'G332', 'logitech', 'Audífonos con micrófono G332 para juegos.', 'Los audífonos Logitech G332 para juegos producen un gran sonido que permite sumergirse en el juego. Vive la intensidad de una experiencia de juego completa donde lo oyes todo y te oyen todos.', 'Los grandes transductores de audio de 50 mm producen un sonido completamente expansivo para una experiencia de juego más inmersiva. Por fin tus juegos favoritos sonarán como se concibieron: asombrosamente.', 'Todo en estos audífonos es confort: Las ligeras copas y diadema de piel sintética de lujo se han creado para eliminar la presión en las orejas. Las copas giran hasta 90 grados para mayor confort. Ajusta el volumen confortable y rápidamente en cualquier plataforma con la rueda de volumen montada en copa.', '1626767642_g332-gallery-1.webp', '450.00', 5),
(34, 'G233 PRODIGY', 'logitech', 'Audífonos con micrófono G233 para juegos.', 'Los jugadores requieren audio totalmente envolvente. Y con razón, ya que con cada nuevo título mejora el sonido. G233 ofrece un increíble desempeño de audio en un diseño extremadamente ligero, duradero y confortable.', 'Los transductores Pro-G producen graves potentes y agudos claros gracias a la malla híbrida que reduce drásticamente la distorsión. Las copas de G233 también tienen un puerto acústico situado detrás del transductor para producir un sonido espacial aún más dinámico.', 'Con un peso de 259 g, los audífonos G233 están hechos de policarbonato ligero inyectado con fibra de vidrio, acero inoxidable y nylon TR-90. Las almohadillas de malla deportiva envuelven el oído con la presión justa para una sujeción confortable y transpirable.', '1626767669_g233-prodigy-gaming-headset65207.webp', '500.00', 5),
(35, 'G231 PRODIGY', 'logitech', 'Audífonos estéreo con micrófono G231 para juegos.', 'Las sesiones de juego maratonianas suelen ser acaloradas... y sudorosas. Hemos cubierto las copas de G231 con un material suave de alto desempeño, cuidadosamente seleccionado para un uso confortable hora tras hora. Las cubiertas se quitan fácilmente para lavarlas y mantener los audífonos impecables.', 'El diseño de las copas es ligero pero no reduce la calidad del audio. Un ensamblaje ligero y equilibrado facilita la concentración en el juego. Hasta podrías olvidar que estás usando unos juegos audífonos con micrófono.', 'Asegúrate de que te reciben alto y claro sin la distracción del ruido de fondo. Ajusta el micrófono para que capte únicamente tu voz y tu equipo te oiga alto y claro.', '1626767717_g231-gallery-1.webp', '500.00', 5),
(36, 'G430', 'logitech', 'Audífonos con micrófono G430 con sonido envolvente 7.1 para juegos.', 'Sumérgete en audio asombroso. G430 incluye modos de sonido envolvente Dolby Headphone y DTS Headphone:X con Logitech Gaming Software (LGS). Experimenta audio de 360 grados que te hace sentirte en el centro de la acción, para poder detectar enemigos a tu alrededor.', 'La copa pivota para ajustarse a tu oreja, y gira hasta 90 grados para quedar totalmente plana. Este diseño hace los audífonos más fáciles de transportar y más confortables cuando los tienes sobre el cuello.', 'Las almohadillas de G430 están recubiertas con una funda de tela de desempeño deportivo para ofrecerte un tacto suave y agradable incluso tras horas de uso. La funda de tela se quita fácilmente para lavarla y mantener los audífonos impecables.', '1626767745_g430-gallery-1.webp', '550.50', 5),
(37, 'Z623', 'logitech', 'Sistema de bocinas Z623 con subwoofer.', 'El sonido con certificación THX® tiene una potencia de 400 watts (pico)/200 watts (RMS) para enriquecer la música, las películas y los videojuegos (todo esto desde tu escritorio). ', 'Este sistema 2.1 brinda un sonido nítido y graves atronadores para música, películas y videojuegos. Escucha las notas altas claramente a través de las bocinas satélite y los graves profundos mediante el subwoofer con puerto lateral. Sonido potente que puedes sentir.', 'CONÉCTATE A TU MODO Tres conexiones para el triple de diversión Las dos tomas de 3,5 mm y las entradas de RCA te permiten conectar tus dispositivos favoritos, como la TV, la computadora, el teléfono inteligente e incluso tu consola de videojuegos. Puedes mantener todos los dispositivos conectados e intercalarlos según lo desees.', '1626767819_speaker-system-z6235.webp', '1600.00', 10),
(38, 'G560', 'logitech', 'Altavoces G560 lightsync para juegos en pc.', 'La tecnología RGB LIGHTSYNC te sumerge en el entorno con una iluminación que reacciona automáticamente al contenido de juego. La luz y el color se pueden sincronizar con lo que aparece en la pantalla, cambiar al ritmo del audio o producir efectos especiales de iluminación programados por los desarrolladores.', 'Elige un área del monitor y asígnala a cualquiera de las cuatro zonas de iluminación usando Logitech G HUB. Elige una sección cualquiera de la pantalla y asígnala a una de las cuatro áreas: izquierda, derecha, frontal y posterior. El motor de LIGHTSYNC lee los colores de los píxeles en pantalla y los coordina dinámicamente con los altavoces en tiempo real.', 'Proyecta el mundo del juego en tu habitación.Los desarrolladores de juegos trabajan con nuestro SDK LIGHTSYNC para programar los efectos de color y animación de cada juego para realzar con RGB los espectaculares momentos que crean. Tus juegos favoritos. A plena luz.', '1626767850_g560-gallery-1.webp', '1700.00', 5),
(39, 'G840 K/DA', 'logitech', 'Alfombrilla de mouse G840 XL para juegos.', 'La gran superficie de G840 te ofrece más espacio para jugar que nunca. Juega con libertad de configuración, sin las limitaciones de alfombrillas más pequeñas.', 'La superficie hecha para el desempeño proporciona uniformidad y precisión máximas con mouse para juegos ya que ofrece imágenes de sensor óptimas para convertir el movimiento del mouse en movimiento del cursor incluso a altas velocidades.', 'Ofrece las sensaciones necesarias para \"sentir\" el movimiento del mouse. Usa la memoria muscular para apuntar con acierto y optimiza tanto pequeños movimientos rápidos como el control a baja velocidad.', '1626767969_g840-kda-gallery-1.webp', '299.99', 10),
(40, 'POWERPLAY', 'logitech', 'Sistema inalámbrico de carga powerplay.', 'Con las tecnologías POWERPLAY y LIGHTSPEED integradas, Logitech G salva los obstáculos para los juegos inalámbricos de alto desempeño. El retardo de entrada, las desconexiones inalámbricas y las baterías agotadas son cosas del pasado. ', 'El módulo POWERCORE incluido habilita mouse inalámbricos compatibles para POWERPLAY. Funciona con los mouse inalámbricos para juegos G903 y G703. Cambia al módulo magnético POWERCORE y ya puedes empezar a cargar de forma inalámbrica.', 'El logo G se ilumina en un resplandeciente color RGB LIGHTSYNC que responde a la acción de juego de muchos títulos. Usa Logitech G HUB y configura las animaciones y el color de iluminación con hasta 16,8 millones de colores a elegir. Puedes sincronizar los efectos de iluminación y colores con mouse, teclados y audífonos con micrófono Logitech G.', '1626768030_powerplay-gallery-1-nb.webp', '999.00', 15),
(41, 'G640', 'logitech', 'Alfombrilla de tela grande para juegos.', 'Al usar valores de dpi bajos te beneficias de la resistencia moderada que los pies del mouse encuentran al iniciar o detener un movimiento rápido o repentino como suele suceder en los juegos de dpi bajos. G640 ofrece la fricción justa para maniobras de juegos con valores bajos de dpi.', 'Como sabemos que algunos diseños y patrones pueden interferir con el desempeño de los sensores, la alfombrilla de tela G640 está diseñada para garantizar un desempeño uniforme. De extremo a extremo, la alfombrilla posee una textura de superficie uniforme y limpia para el seguimiento fluido en toda la superficie.', 'G640 brinda a los jugadores la posibilidad de obtener una precisión mejorada del sensor. La superficie de G640 tiene una textura similar a la del entorno óptimo de prueba para los mouse Logitech G.', '1626768070_g640-gallery-1.webp', '299.99', 10),
(42, 'HARPOON RGB PRO', 'corsair', 'Mouse para juegos fps/moba harpoon rgb pro.', 'Con una cómoda forma contorneada con agarres laterales de goma y un peso increíblemente ligero (85 g), el HARPOON RGB PRO es perfecto para jugar infinidad de horas sin esfuerzo.', 'Disfrute del control preciso que necesita para ganar gracias a un sensor óptico de 12 000 ppp y una gran durabilidad con conmutadores Omron de alto rendimiento que alcanzan más de 20 millones de clics.', 'Control de iluminación RGB viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, gracias a su compatibilidad con periféricos, refrigeradores, ventiladores y otros productos de CORSAIR.', '1626768333_g935-gallery-1.webp', '259.99', 10),
(43, 'SCIMITAR RGB ELITE', 'corsair', 'Mouse óptico para juegos moba/mmo scimitar rgb elite', 'Equipado con un sensor óptico personalizado PixArt PMW3391 de 18.000 ppp nativos ajustables en incrementos de resolución de 1 ppp para un seguimiento personalizable y muy preciso.', 'Los conmutadores Omron con capacidad de hasta 50 millones de clics, la rueda de desplazamiento resistente y el cable trenzado del SCIMITAR RGB ELITE garantizan que resista el desgaste asociado con las sesiones de juego intensivas.', 'Equipado con un sensor óptico personalizado PixArt PMW3391 de 18.000 ppp nativos ajustables en incrementos de resolución de 1 ppp para un seguimiento personalizable y muy preciso.', '1626768433_-CH-9304211-NA-Gallery-Scimitar-ELITE-BLK-01.webp', '499.99', 10),
(44, 'NIGHTSWORD RGB', 'corsair', 'Mouse personalizable para juegos fps/moba nightsword rgb', 'El software exclusivo de CORSAIR detecta automáticamente el centro de gravedad del ratón en tiempo real, de modo que pueda ajustar el peso entre 119 g y 141 g, así como ajustar el equilibrio para que se ajuste perfectamente a su agarre.', 'Manténgase concentrado y acierte en todos los objetivos. Cuente con una personalización absoluta de la sensibilidad y un seguimiento ultrapreciso con un sensor óptico Pixart PMW3391 con incrementos de resolución de 1 ppp.', 'Control de iluminación RGB viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, gracias a su compatibilidad con periféricos, refrigeradores, ventiladores y otros productos de CORSAIR.', '1626768544_-CH-9306011-NA-Gallery-NIGHTSWORD-RGB-01.webp', '399.00', 15),
(45, 'IRONCLAW RGB', 'corsair', 'Mouse para juegos ironclaw rgb fps/moba.', 'El ratón para juegos IRONCLAW RGB tan solo pesa 105 g y su forma se ha esculpido específicamente para agarrar con la palma y con casi todo tipo de manos. Diseñado para perdurar, con conmutadores Omron que alcanzan más de 50 millones de clics.', 'Control de iluminación RGB viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, gracias a su compatibilidad con periféricos, refrigeradores, ventiladores y otros productos de CORSAIR.', 'Equipado con un sensor óptico Pixart PMW3391 personalizado de 18.000 ppp de precisión nativa con incrementos de resolución de 1 ppp. El ratón para juegos Ironclaw RGB ofrece un seguimiento ultrapreciso y un rendimiento de juego de primer nivel.', '1626768599_-CH-9307011-NA-Gallery-IRONCLAW-RGB-01.webp', '499.00', 10),
(46, 'M55 RGB PRO', 'corsair', 'Mouse ambidiestro para juegos y con varios agarres m55 rgb pro.', 'Con un peso de solo 86 g, el diseño ambidiestro ligero y versátil del M55 RGB PRO le permite jugar al máximo nivel con cualquier mano con el agarre más cómodo, ya sea la palma, los dedos o la punta de los dedos.', 'El diseño duradero con conmutadores Omron con capacidad para 50 millones de clics y un cable trenzado dota al M55 RGB PRO de la fuerza necesaria para soportar varios años de sesiones de juego intensas.', 'Control de iluminación RGB viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, gracias a su compatibilidad con periféricos, refrigeradores, ventiladores y otros productos de CORSAIR.', '1626768635_-CH-9308011-NA-Gallery-M55-RGB-PRO-BLACK-01.webp', '599.00', 15),
(47, 'M65 RGB ELITE', 'corsair', 'Mouse para juegos fps m65 rgb elite ajustable.', 'El ratón para juegos CORSAIR M65 RGB ELITE ajustable es el ratón para juegos FPS de CORSAIR más avanzado hasta el momento, creado a partir de una resistente estructura de aluminio y equipado con un moderno sensor óptico de 18 000 DPI.', '18 000 ppp nativos ajustables en pasos de resolución de 1 ppp que le ofrecen una personalización completa de la sensibilidad y un rastreo ultrapreciso, convirtiendo el M65 RGB Elite en un ratón de juego perfecto para FPS.', 'Estructura de aluminio anodizado premium y duradero diseñada para soportar toda una vida de juegos. Conmutadores Omron de alto rendimiento que alcanzan más de 50 millones de clics.', '1626768705_-CH-9309111-NA-Gallery-M65-RGB-ELITE-WHT-01.webp', '499.99', 10),
(48, 'HARPOON RGB WIRELESS', 'corsair', 'Mouse para juegos harpoon rgb wireless.', ' SKU CH-9311011-NA Ratón para juegos HARPOON RGB WIRELESS El ratón para juegos CORSAIR HARPOON RGB WIRELESS le permite elegir cómo jugar, con la capacidad de conectarse fácilmente al PC a través de una tecnología ultrarrápida, la TECNOLOGÍA SLIPSTREAM CORSAIR WIRELESS en menos de 1 ms, Bluetooth o conexión por cable USB', 'El sencillo proceso de configuración permite empezar a jugar más rápidamente: basta con conectar el adaptador inalámbrico a un puerto USB y activar el ratón o conectar mediante Bluetooth de baja latencia o con cable USB.', 'Juegue sin cables durante 60 horas* o conecte un cable para seguir jugando. Conmutadores Omron ultrarresistentes que alcanzan más de 50 millones de clics, además de un sensor óptico de 10 000 ppp de alto rendimiento con el que sabrá que podrá disparar en el momento oportuno.', '1626768765_-CH-9311011-NA-Gallery-Harpoon-RGB-Wireless-01.webp', '799.99', 10),
(49, 'DARK CORE RGB PRO', 'corsair', 'Mouse para juegos inalámbrico dark core rgb pro.', 'El CORSAIR DARK CORE RGB PRO le ayuda a ganar sin cables, y cuenta con el sistema SLIPSTREAM WIRELESS de menos de 1 ms, un sensor óptico personalizado de 18.000 ppp optimizado para ratones inalámbricos y la tecnología de sondeo avanzada a un máximo de 2.000 Hz.', 'Equipado con un sensor óptico PixArt PAW3392 personalizado de 18.000 ppp, optimizado para sistemas inalámbricos con un consumo de energía extremadamente bajo y personalizable en incrementos de resolución de 1 ppp.', 'La tecnología de sondeo avanzada se comunica con el PC a un máximo de 2.000 Hz, el doble de la velocidad de los ratones para juegos estándar.', '1626768828_-CH-9315411-NA-Gallery-DARK-CORE-RGB-PRO-01.webp', '799.99', 5),
(50, 'IRONCLAW RGB WIRELESS', 'corsair', 'Mouse para juegos ironclaw rgb wireless.', 'El ratón de juego CORSAIR IRONCLAW RGB WIRELESS combina un sensor óptico de 18 000 ppp nativos con un cómodo agarre para la palma. Puede conectarlo fácilmente al PC a través de una tecnología ultrarrápida, la TECNOLOGÍA SLIPSTREAM CORSAIR WIRELESS en menos de 1 ms, Bluetooth o conexión por cable USB.', 'Un sensor óptico personalizado Pixart PMW3391 de 18.000 ppp nativos ofrece un seguimiento ultrapreciso ajustable en incrementos de resolución de 1 ppp para una personalización completa de la sensibilidad.', 'Control de iluminación RGB viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, gracias a su compatibilidad con periféricos, refrigeradores, ventiladores y otros productos de CORSAIR.', '1626768872_-CH-9317011-NA-Gallery-IRONCLAW-RGB-WIRELESS-01.webp', '600.00', 15);
INSERT INTO `productos` (`id`, `nombreP`, `marcaP`, `descripcionP`, `descripcionP1`, `descripcionP2`, `descripcionP3`, `imagenP`, `precioP`, `existenciaP`) VALUES
(51, 'KATAR PRO WIRELESS', 'corsair', 'Mouse para juegos katar pro wireless.', 'Disfrute del diseño ligero y del rendimiento de un peso pesado del ratón para juegos CORSAIR KATAR PRO WIRELESS, que se conecta mediante la rapidísima tecnología SLIPSTREAM WIRELESS o Bluetooth de baja latencia. Solo pesa 96 g. Su forma simétrica compacta es perfecta para cualquier estilo de agarre.', 'Juegue con la tecnología ultrarrápida SLIPSTREAM CORSAIR WIRELESS inferior a 1 ms, o conéctalo a una amplia variedad de dispositivos con Bluetooth de baja latencia con una sola pila AA.', 'El KATAR PRO WIRELESS, con solo 96 g de peso, es perfecto para que el usuario pueda pasar varias horas jugando a FPS o MOBA trepidantes. La forma simétrica y compacta hace que sea estupendo para quienes agarran el ratón con la punta de los dedos o con todo el dedo.', '1626768965_-base-katar-pro-wireless-config-Gallery-KATAR-PRO-WIRELESS-01.png_515Wx515H', '700.00', 10),
(52, 'HARPOON RGB', 'corsair', 'Mouse harpoon rgb ratón para juegos.', 'El ratón HARPOON RGB ha sido diseñado para ofrecerle el máximo rendimiento. Introduce un sensor de juego óptico de 6.000 DPI con seguimiento avanzado para que pueda disfrutar de un control de precisión, y un diseño ligero y estilizado para facilitar los movimientos más rápidos.', 'El ratón HARPOON RGB es increíblemente ligero, solo pesa 85 g, por lo que puede jugar durante más tiempo cómodamente gracias a su forma contorneada y a los agarres laterales de goma.', 'El software CORSAIR iCUE permite controlar la iluminación RGB viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, entre periféricos, refrigeradores, ventiladores y otros productos compatibles de CORSAIR.', '1626769014_-CH-9301011-NA-Gallery-HARPOON-RGB-01.webp', '399.00', 15),
(53, 'M65 PRO RGB', 'corsair', 'Mouse para juegos fps m65 pro rgb.', 'El M65 PRO RGB es un ratón para juegos FPS de competición que incorpora la tecnología que precisas para ganar, la personalización que necesitas para hacerlo tuyo y un diseño de calidad duradero.', 'El ratón de juego personalizable CORSAIR M65 PRO RGB tiene una estructura de aluminio anodizado premium y duradero con diseño para soportar toda una vida de juegos.', 'Los ocho botones completamente programables permiten configuraciones totalmente personalizadas para sacar el máximo partido a sus partidas. Un botón de francotirador convenientemente ubicado le permite reducir la sensibilidad al instante en los disparos cruciales.', '1626769074_-CH-9300011-NA-Gallery-M65-PRO-RGB-BLK-01.png_515Wx515H', '499.00', 10),
(54, 'SABRE RGB PRO', 'corsair', 'Mouse óptico para juegos sabre rgb pro champion series.', 'El ratón para juegos CORSAIR SABRE RGB PRO ha sido diseñado siguiendo las indicaciones de los profesionales de los deportes electrónicos (eSports), pesa solo 74 g y está equipado con un cable Paracord flexible que reduce el arrastre, por los que sus movimientos serán siempre ágiles y sin obstáculos.', 'Equípese con el SABRE RGB PRO, un ratón para juegos ligero y apto para competición, equipado con un cable Paracord flexible que reduce el arrastre y botones QUICKSTRIKE con respuesta ultrarrápida.', 'La tecnología de hiperprocesamiento CORSAIR AXON transmite sus movimientos y clics al PC hasta ocho veces más rápido que los ratones para juegos convencionales, con un sondeo de 8.000 Hz.', '1626769139_-base-sabre-rgb-pro-champion-Gallery-CH-9303111-01.png_515Wx515H', '499.99', 10),
(55, 'GLAIVE RGB PRO', 'corsair', 'Mouse para juegos glaive rgb pro.', 'El ratón de juego CORSAIR GLAIVE RGB PRO combina un alto rendimiento con gran comodidad, desarrollado con una forma contorneada diseñada para jugar de manera prolongada, y con un sensor óptico ultrapreciso de calidad de juego de 18 000 ppp.', 'El ratón de juego GLAIVE RGB PRO combina un alto rendimiento con gran comodidad, con una forma contorneada ideal para jugar de manera prolongada. Elija entre los tres agarres intercambiables incluidos para la zona del pulgar, para conseguir un ajuste perfecto.', 'Siempre dará lo mejor de sí mismo gracias a un sensor óptico ultrapreciso de 18 000 ppp nativos y conmutadores Omron de alto rendimiento que alcanzan más de 50 millones de clics.', '1626769178_-CH-9302211-NA-Gallery-GLAIVE-RGB-PRO-BLACK-01.webp', '450.99', 5),
(56, 'SCIMITAR PRO RGB', 'corsair', 'Mouse para juegos moba/mmo óptico scimitar pro rgb.', 'El ratón para juegos SCIMITAR PRO RGB mejora las partidas gracias al sistema de control de botones de macro Key Slider™ personalizable, un sensor óptico con una precisión nativa de 16 000 ppp y almacenamiento de perfiles interno.', 'Ajuste la posición de los botones hasta 8 mm y bloquéelas con el sistema de control de macros (pendiente de patente) que pone todas las teclas a su alcance, independientemente del estilo de juego. Las teclas laterales con textura mejoran el agarre y el tacto para conseguir una respuesta táctil constante y un control preciso.', 'Los 12 botones laterales mecánicos se han diseñado para ajustarse a las especificaciones profesionales y ofrecer una respuesta táctil constante y un accionamiento preciso. Las teclas laterales con textura mejoran el agarre y el tacto.', '1626769222_-CH-9304011-AP-Gallery-Scimitar-PRO-01.webp', '500.00', 5),
(57, 'KATAR PRO', 'corsair', 'Mouse ultraligero para juegos katar pro.', 'Disfrute del diseño ligero y del rendimiento de peso pesado del ratón ultraligero para juegos CORSAIR KATAR PRO. Solo pesa 69 g, tiene una forma simétrica compacta y cuenta con un sensor óptico preciso de 12.400 ppp.', 'El KATAR PRO, con solo 69 g de peso, es extremadamente ligero y ágil para que el usuario pueda pasar varias horas jugando a FPS o MOBA trepidantes. La forma simétrica y compacta hace que sea estupendo para quienes agarran el ratón con la punta de los dedos o con todo el dedo.', 'El sensor óptico personalizado PixArt de 12.400 ppp ofrece la precisión y el seguimiento de alta precisión necesarios para ganar.', '1626769296_-base-katar-pro-config-Gallery-KATAR-PRO-WIRED-01.png_515Wx515H', '600.00', 15),
(58, 'SABRE PRO', 'corsair', 'Mouse óptico para juegos sabre pro champion series.', 'El ratón para juegos CORSAIR SABRE PRO ha sido diseñado y probado por profesionales de los deportes electrónicos (eSports), pesa solamente 69 g y está equipado con un cable Paracord flexible que reduce el arrastre, por los que sus movimientos serán siempre ágiles y rápidos.', 'Equípese con el SABRE PRO, un ratón para juegos ligero y apto para competición, equipado con un cable Paracord flexible que reduce el arrastre y botones QUICKSTRIKE con respuesta ultrarrápida.', 'La tecnología de hiperprocesamiento CORSAIR AXON transmite sus movimientos y clics al PC hasta ocho veces más rápido que los ratones para juegos convencionales, con un sondeo de 8.000 Hz.', '1626769328_-base-sabre-pro-champion-Gallery-CH-9303101-01.png_515Wx515H', '499.99', 10),
(59, 'KATAR PRO XT', 'corsair', 'Mouse ultraligero para juegos katar pro xt.', 'Disfrute del diseño ligero y del rendimiento de peso pesado del ratón ultraligero para juegos CORSAIR KATAR PRO XT. Solo pesa 73 g, tiene una forma simétrica compacta y cuenta con un sensor óptico extremadamente preciso de 18.000 ppp.', 'El KATAR PRO XT, con solo 73 g de peso, es extremadamente ligero y ágil para que el usuario pueda pasar varias horas jugando a FPS o MOBA trepidantes. La forma simétrica y compacta hace que sea estupendo para quienes agarran el ratón con la punta de los dedos o con todo el dedo. ', 'Los botones CORSAIR QUICKSTRIKE presentan un diseño de tensión por muelles con disparidad nula entre los botones del ratón (izquierdo y derecho) y sus conmutadores, de forma que todos sus clics, disparos y hechizos son más rápidos que nunca.', '1626769393_-base-katar-pro-xt-config-Gallery-KATAR-PRO-XT-01.png_515Wx515H', '550.99', 15),
(60, 'STRAFE RGB MK.2', 'corsair', 'El teclado mecánico CORSAIR STRAFE RGB MK.2 de última generación.', 'El teclado mecánico CORSAIR STRAFE RGB MK.2 de última generación incorpora interruptores 100 % CHERRY® MX RGB y 8 MB de almacenamiento interno de perfiles para llevar sus perfiles de juegos donde quiera que vaya.', 'El software CORSAIR iCUE permite una sofisticada programación de macros y todo el control de la retroiluminación brillante RGB por tecla con sincronización de toda la iluminación del sistema. Lleve el espectáculo a todas partes con 8 MB de almacenamiento interno de perfiles.  Pruebe los perfiles de iluminación con iCUE.', 'Los interruptores de teclas CHERRY® MX Red, con una respuesta lineal y suave y con un accionamiento preciso, pueden responder a sus reflejos en situaciones críticas.', '1626769539_-CH-9309111-NA-Gallery-M65-RGB-ELITE-WHT-01.webp', '800.99', 20),
(61, 'K70 RGB MK.2', 'corsair', 'El CORSAIR K70 RGB MK.2 es un teclado mecánico premium.', 'El CORSAIR K70 RGB MK.2 es un teclado mecánico premium para juegos diseñado para durar, con una estructura de aluminio, interruptores 100 % CHERRY® MX y 8 MB de almacenamiento interno de perfiles.', 'Permite el acceso a un máximo de tres perfiles almacenados para usarlos en cualquier parte, independientemente del software externo.', 'Control de iluminación RGB viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, gracias a su compatibilidad con periféricos, refrigeradores, ventiladores y otros productos de CORSAIR.', '1626769628_-CH-9109010-NA-Gallery-K70-RGB-MK2-01.webp', '900.00', 10),
(62, 'K70 RGB MK.2 Low Profile', 'corsair', 'El teclado mecánico para juegos CORSAIR K70 RGB MK.2 Low Profile.', 'El teclado mecánico para juegos CORSAIR K70 RGB MK.2 Low Profile, combina la comodidad sin fin de las teclas de bajo perfil y reducido desplazamiento con el rendimiento de los interruptores de tecla mecánicos CHERRY® MX y la espectacular iluminación RGB.', 'La comodidad de los teclados de juego ha llegado a otro nivel! Mediante la optimización de la posición de la palma gracias a unas teclas más bajas y controles multimedia optimizados para la accesibilidad, con el nuevo diseño del teclado bajo, sus palmas estarán casi en paralelo, consiguiendo una postura más natural.', 'Disfrute del rendimiento que necesita con los interruptores mecánicos Low Profile CHERRY® MX RED exclusivos de CORSAIR. El diseño de perfil bajo ofrece la precisión que se espera de un interruptor CHERRY® con un 35 % menos de altura en las teclas.', '1626769703_-CH-9109017-NA-Gallery-K70-RGB-MK2-LP-01.webp', '999.00', 10),
(63, 'K70 RGB MK.2 SE', 'corsair', 'El CORSAIR K70 RGB MK.2 SE es un teclado mecánico premium.', 'El CORSAIR K70 RGB MK.2 SE es un teclado mecánico premium para juegos diseñado para durar, con una estructura de aluminio plateado, interruptores CHERRY® MX Speed, teclas de doble moldeado y una increíble retroiluminación dinámica RGB por tecla.', 'Destaque gracias a la estructura especial de aluminio plateado cepillado y anodizado y a las sorprendentes teclas blancas de doble moldeado de precisión. Diseñada para llamar la atención y soportar toda una vida de juegos.', 'Lleve todas las macros, perfiles de iluminación y métodos abreviados de teclado donde quiera que vaya, gracias a los tres perfiles almacenados que funcionan sin necesidad de usar más software ni controladores.', '1626769782_-CH-9109114-NA-Gallery-K70-RGB-MK2-SE-01.webp', '1099.00', 15),
(64, 'K60 RGB PRO', 'corsair', 'El teclado mecánico de juego CORSAIR K60 RGB PRO.', 'El teclado mecánico de juego CORSAIR K60 RGB PRO se ha diseñado pensando en el estilo y la consistencia, con una estructura de aluminio cepillado duradera e interruptores mecánicos CHERRY VIOLA que permiten que reluzca la brillante retroiluminación RGB en cada tecla', 'Control de iluminación RGB dinámico y vívido, programación macro sofisticada y sincronización de iluminación del sistema completo compatible con periféricos, refrigeradores, ventiladores y más de CORSAIR.', 'Con el software CORSAIR iCUE convierte todo su equipo en un ecosistema uniforme y completamente inmersivo que podrá controlar de forma intuitiva.', '1626769820_-base-k60-rgb-pro-config-Gallery-K60-RGB-PRO-01.png_515Wx515H', '799.99', 10),
(65, 'K60 RGB PRO SE', 'corsair', 'El teclado mecánico de juego CORSAIR K60 RGB PRO SE.', 'El teclado mecánico de juego CORSAIR K60 RGB PRO SE se ha diseñado con una estructura de aluminio cepillado duradera e interruptores mecánicos CHERRY VIOLA que permiten que reluzca la brillante retroiluminación RGB en cada tecla.', 'Control de iluminación RGB viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, gracias a su compatibilidad con periféricos, refrigeradores, ventiladores y otros productos de CORSAIR. ', 'Con décadas de experiencia, CHERRY presenta una tradición histórica como la primera opción de los jugadores y profesionales de los e-sports en todo el mundo. Los interruptores CHERRY, fabricados y diseñados en Alemania, se diseñan para soportar toda una vida de juegos, con una fiabilidad garantizada y unas pulsaciones de tecla consistentes durante toda la vida del interruptor.', '1626769912_-base-k60-rgb-pro-se-config-Gallery-K60-RGB-PRO-SE-01.png_515Wx515H', '899.99', 5),
(66, 'K95 RGB PLATINUM XT', 'corsair', 'El teclado mecánico para juegos CORSAIR K95 RGB PLATINUM XT.', 'El teclado mecánico para juegos CORSAIR K95 RGB PLATINUM XT sumerge su escritorio en una iluminación RGB dinámica con iluminación en cada tecla, equipado con un conjunto de teclas PBT de gran duración y seis teclas macro exclusivas con integración del software Elgato Stream Deck.', 'La retroiluminación RGB en cada tecla y el sistema LightEdge de 19 zonas proporcionan efectos de iluminación vivos y dinámicos con personalización prácticamente ilimitada.', 'Una estructura de aluminio anodizado con un conjunto de 104/105 teclas de doble inyectado de PBT ultraduradero con un diseño para soportar toda una vida de juegos.', '1626769943_-CH-9127412-NA-Gallery-K95-PLATINUM-RGB-XT-01.webp', '1259.99', 10),
(67, 'K100 RGB', 'corsair', 'El incomparable teclado mecánico para juegos CORSAIR K100 RGB.', 'El incomparable teclado mecánico para juegos CORSAIR K100 RGB combina un impresionante diseño de aluminio, iluminación RGB en cada tecla con la potente tecnología de hiperprocesamiento CORSAIR AXON y los interruptores de tecla CHERRY MX SPEED.', 'El elegante diseño del K100 RGB cuenta con una robusta estructura de aluminio y retroiluminación dinámica por cada tecla per-clave retroiluminación RGB rematado por LightEdge RGB de 44 zonas y tres lados.', 'La tecnología de hiperprocesamiento CORSAIR AXON ofrece la más avanzada experiencia de teclado para juegos de CORSAIR gracias a una transmisión de datos hasta cuatro veces más rápida con sondeo avanzado nativo de 4.000 Hz y escaneo de teclas de 4.000 Hz, al mismo tiempo que ejecuta efectos de iluminación 20 capas.', '1626769972_-CH-912A014-NA-Gallery-K100-RGB-01.png_515Wx515H', '1599.99', 10),
(68, 'K63', 'corsair', 'Teclado mecánico inalámbrico de juego CORSAIR K63.', 'Disfrute de la libertad de juego definitiva con el teclado mecánico inalámbrico de juego CORSAIR K63, con tecnología inalámbrica ultrarrápida de 2,4 GHz y 1 ms e interruptores de tecle mecánicos CHERRY® MX en un diseño tenkeyless portátil.\"', 'Use una conexión USB con cable, el Bluetooth® inalámbrico de baja latencia, o la tecnología inalámbrica optimizada para juegos de 2,4 GHz, 1 ms y ultrarrápida.', 'El software CORSAIR iCUE permite controlar la iluminación viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, entre periféricos, refrigeradores, ventiladores y otros productos compatibles de CORSAIR.', '1626770028_-CH-9145030-NA-Gallery-K63-Wireless-NA-01.webp', '888.99', 10),
(69, ' K57 RGB Wireless', 'corsair', 'teclado de juego K57 RGB Wireless.', 'Ilumine sus partidas en modo inalámbrico con el teclado de juego K57 RGB Wireless, con tecnología SLIPSTREAM WIRELESS de menos de 1 ms y una retroiluminación RGB brillante en cada tecla con LED CAPELLIX.', 'Juegue de forma inalámbrica con una iluminación RGB completa hasta 35 horas (y hasta 175 sin iluminación). Elija entre 18 efectos de iluminación predeterminados diferentes de forma inalámbrica o controle cada una de las teclas iluminadas individualmente en el modo con cable.', 'El software CORSAIR iCUE convierte todo su equipo en un ecosistema uniforme y completamente inmersivo que podrá controlar de forma intuitiva.', '1626770100_-CH-925C015-NA-Gallery-K57-RGB-WIRELESS-NA-01.webp', '799.99', 15),
(70, 'K55 RGB', 'corsair', 'Teclado para juegos K55 RGB.', 'El K55 RGB lleva el rendimiento a un nuevo nivel. Los modos de retroiluminación RGB intuitivos, sus 6 teclas macro específicas, el efecto antifantasmas multitecla y sus controles multimedia programables sobre la marcha ofrecen un gran control y capacidad de personalización, elementos esenciales para lograr la victoria.', 'El diseño con protección IP42 contra el polvo y los derrames ayuda a evitar accidentes para no tenga que interrumpir su juego.', 'El software CORSAIR iCUE permite controlar la iluminación viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, entre periféricos, refrigeradores, ventiladores y otros productos compatibles de CORSAIR.', '1626770145_-CH-9206015-SP-Gallery-K55-RGB-01.webp', '700.99', 10),
(71, ' K55 + HARPOON RGB', 'corsair', 'Pack de teclado y ratón K55 + HARPOON RGB.', 'El pack de teclado y ratón para juegos K55 + HARPOON RGB es su primer paso para convertirse en ganador. Presenta teclas de macro programables, un sensor de ratón de 6000 dpi de alto rendimiento y compatibilidad completa con CUE.', 'Los modos de retroiluminación RGB intuitivos, sus 6 teclas macro específicas, el efecto antifantasmas multitecla y sus controles multimedia ofrecen un gran control y capacidad de personalización, elementos esenciales para lograr la victoria. El K55 RGB lleva el rendimiento a un nuevo nivel.', 'El modo de bloqueo de teclas de Windows del K55 RGB elimina distracciones al desactivar la tecla de Windows mientras juega, y las patas plegables de la parte inferior del teclado permiten una colocación óptima de las manos.', '1626770187_-CH-9206115-SP-Gallery-K55-RGB-Harpoon-NA-01.webp', '1099.99', 15),
(72, 'K68 RGB', 'corsair', 'El teclado mecánico de larga duración CORSAIR K68 RGB.', 'El teclado mecánico de larga duración CORSAIR K68 RGB combina una viva retroiluminación RGB en cada tecla, resistencia al agua y al polvo de hasta IP32 e interruptores de tecla 100 % CHERRY MX, para que pueda seguir jugando pase lo que pase.', 'Los interruptores de tecla CHERRY MX de fabricación alemana le ofrecen la fiabilidad y la precisión que necesita con una respuesta lineal y fluida.', 'El software CORSAIR iCUE permite controlar la iluminación viva y dinámica, con una sofisticada programación de macros y la posibilidad de sincronizar toda la iluminación del sistema, entre periféricos, refrigeradores, ventiladores y otros productos compatibles de CORSAIR.', '1626770217_-CH-9102010-SP-Gallery-K68-RGB-01.webp', '800.00', 5),
(73, 'K70 LUX', 'corsair', 'El teclado K70 LUX tiene interruptores de tecla CHERRY® MX Red.', 'El teclado K70 LUX tiene interruptores de tecla CHERRY® MX Red reforzados con un chasis de aluminio ligero. Teclas con fuentes grandes con una vibrante retroiluminación regulable mediante el software CUE.\"', 'Elige entre los tres tipos de interruptor de tecla Cherry MX el que mejor se adapte a tu estilo de juego, exprésate con la retroiluminación programable y las teclas con fuentes grandes y transforma completamente tu manera de jugar con las macros programables.', 'Construidos en un resistente chasis de aluminio, los teclados Corsair LUX proporcionan la mejor experiencia para todas las situaciones.', '1626770256_-CH-9101020-SP-Gallery-K70-LUX-RED-NA-01.webp', '799.99', 10),
(74, 'K95 RGB PLATINUM', 'corsair', 'El teclado CORSAIR K95 RGB PLATINUM incluye interruptores CHERRY® MX Brown', 'El teclado CORSAIR K95 RGB PLATINUM incluye interruptores CHERRY® MX Brown incorporados en una estructura de aluminio ligero. Almacenamiento de 8 MB con reproducción de iluminación y macros de hardware que permite acceder a perfiles sin software externo.', 'K95 PLATINUM lleva el rendimiento de CORSAIR a otro nivel. Desate un rendimiento irreal con los interruptores mecánicos CHERRY® MX. Almacene y reproduzca macros complejas y efectos de iluminación con cualquier tecla. Abuse de un teclado que soportará toda una vida de uso.', 'Asigne macros de juego complejas a cualquiera de las 6 teclas especiales para macros. Tienen una textura especial que le permitirá encontrarlas fácilmente, además de un contorno que evitará que las pulse sin querer.', '1626770346_-CH-9127012-NA-Gallery-K95-Platinum-001.webp', '1099.00', 15),
(75, 'K65 RGB MINI 60%', 'corsair', 'El teclado mecánico para juegos CORSAIR K65 RGB MINI 60%.', 'El teclado mecánico para juegos CORSAIR K65 RGB MINI 60% combina rendimiento de alto nivel con portabilidad, incluye la tecnología de hiperprocesamiento AXON, interruptores de teclas mecánicos CHERRY MX Red y una capacidad de personalización excepcional en un diseño compacto.', 'El K65 RGB MINI ofrece grandes características comprimidas en un factor de forma del 60 % para encajar fácilmente en cualquier configuración de equipo y jugar con toda la comodidad.', 'Presuma de estilo con retroiluminación RGB dinámica en cada tecla, así como una barra espaciadora radiante opcional, junto con la distribución estándar de la fila inferior para intercambiar juegos de teclas personalizados.', '1626770431_-CH-9194010-NA-Gallery-K65-RGB-MINI-01.png_515Wx515H', '700.99', 10),
(76, 'K70 RAPIDFIRE', 'corsair', 'El teclado K70 RAPIDFIRE incluye interruptores CHERRY® MX Speed.', 'El teclado K70 RAPIDFIRE incluye interruptores CHERRY® MX Speed para ofrecer el rendimiento más rápido entre los teclados mecánicos. Además, incorpora un chasis de aluminio ligero y una retroiluminación LED dinámica y vibrante.', 'Para competir al máximo nivel, necesitas el teclado mecánico más rápido que exista. La capacidad de respuesta instantánea de RAPIDFIRE y su tecnología de erradicación de pulsaciones nulas te permite destacar en el juego gracias a una combinación inédita de velocidad y precisión.', 'La tecnología de registro de todas las teclas y erradicación de las pulsaciones nulas garantiza que el teclado RADIPFIRE pueda seguirte, independientemente de tu velocidad de juego, registrando cada pulsación de tecla correctamente.', '1626770474_-CH-9101024-SP-Gallery-K70-RAPIDFIRE-001.webp', '850.99', 10),
(77, 'VIRTUOSO RGB WIRELESS SE', 'corsair', 'Auriculares para juegos de alta fidelidad VIRTUOSO RGB WIRELESS SE, Plomo.', 'Los CORSAIR VIRTUOSO RGB Wireless SE ofrecen una experiencia de sonido de alta fidelidad y una comodidad continua gracias a las orejeras de espuma con memoria premium y una conectividad hiperrápida con tecnología SLIPSTREAM WIRELESS.', 'Con los VIRTUOSO RGB Wireless podrá escucharlo todo, desde la pisada más fuerte hasta el tono bajo más profundo. Un par de transductores de neodimio de alta densidad de 50 mm ajustados con precisión ofrecen un rango de frecuencia de 20 Hz-40 000 Hz, el doble que casi todos los auriculares de juego.', 'Las almohadillas de espuma viscoelástica premium se adaptan a la forma de su cabeza; además, la banda ligera ofrece una comodidad duradera y suave como una almohada para que pueda jugar durante horas.', '1626770655_-CA-9011180-NA-Gallery-VIRTUOSO-SE-01.webp', '1200.99', 10),
(78, 'VIRTUOSO RGB WIRELESS', 'corsair', 'Auriculares para juegos de alta fidelidad VIRTUOSO RGB WIRELESS, Pearl.', 'Los CORSAIR VIRTUOSO RGB Wireless ofrecen una experiencia de sonido de alta fidelidad y una comodidad continua gracias a las orejeras de espuma con memoria premium y una conectividad hiperrápida con tecnología SLIPSTREAM WIRELESS.', 'Con los VIRTUOSO RGB Wireless podrá escucharlo todo, desde la pisada más fuerte hasta el tono bajo más profundo. Un par de transductores de neodimio de alta densidad de 50 mm ajustados con precisión ofrecen un rango de frecuencia de 20 Hz-40 000 Hz, el doble que casi todos los auriculares de juego.', 'La construcción de aluminio mecanizado consigue que los VIRTUOSO RGB Wireless ofrezcan un diseño ligero, una fuerte durabilidad y la mayor comodidad en una combinación perfecta.', '1626770756_-virtuoso-rgb-config-Gallery-VIRTUOSO-PEARL-01.png_515Wx515H', '1299.99', 10),
(79, 'HS35', 'corsair', 'Auriculares para juegos estéreo HS35, carbón.', 'Póngase los auriculares para juegos estéreo CORSAIR HS35 y disfrute de una voz clara y de un sonido de gran calidad durante horas de juego gracias a la espuma viscoelástica y a las almohadillas ajustables, ideales para PC, PS4, Xbox One, Switch y mucho más.', 'Compatibles con el sonido envolvente Windows Sonic, para que disfrute de un audio inmersivo en 360° que lo trasladará directamente al juego.', 'Solo tiene que conectarlos a un PC, Xbox One*, PS4, Switch o un dispositivo móvil con un conector de 3,5 mm.', '1626770852_-CA-9011195-NA-Gallery-HS35-BLACK-01.webp', '350.00', 5),
(80, 'VOID RGB ELITE Wireless', 'corsair', 'Auriculares premium para juegos VOID RGB ELITE Wireless con sonido envolvente 7.1, carbón.', 'Sumérjase en la acción con los CORSAIR VOID RGB ELITE Wireless, con transductores de audio de neodimio de 50 mm de ajuste personalizado, un cómodo tejido de rejilla de microfibra con almohadillas de espuma con memoria y una conexión inalámbrica de 2,4 GHz.', 'Escúchelo todo con un sonido envolvente 7.1, desde la pisada más ligera hasta la explosión más atronadora, gracias a los transductores de audio de neodimio de alta densidad de 50 mm de ajuste personalizado con un rango de frecuencia ampliado de 20 Hz-30.000 Hz.', 'Diseñados para garantizar la comodidad en largas sesiones de juego, con un tejido de rejilla de microfibra transpirable y lujosas almohadillas de espuma con memoria.', '1626770897_-CA-9011201-NA-Gallery-VOID-RGB-ELITE-WIRELESS-CARBON-01.webp', '999.00', 15),
(81, 'VOID RGB ELITE USB', 'corsair', 'Auriculares premium para juegos VOID RGB ELITE USB con sonido envolvente 7.1, blanco.', ' SKU CA-9011203-NA Auriculares premium para juegos VOID RGB ELITE USB con sonido envolvente 7.1, carbón Sumérjase en la acción con los CORSAIR VOID RGB ELITE USB, con transductores de audio de neodimio de 50 mm de ajuste personalizado, un cómodo tejido de rejilla de microfibra con almohadillas de espuma con memoria y un micrófono omnidireccional.', 'Escúchelo todo con un sonido envolvente 7.1, desde la pisada más ligera hasta la explosión más atronadora, gracias a los transductores de audio de neodimio de alta densidad de 50 mm de ajuste personalizado con un rango de frecuencia ampliado de 20 Hz-30.000 Hz.', 'El software CORSAIR iCUE permite controlar los auriculares de forma precisa con perfiles de audio preajustados, personalizar los ajustes del ecualizador, disfrutar de un sonido envolvente e inmersivo 7.1 y controlar el ruido local.', '1626770933_-CH-9109010-NA-Gallery-K70-RGB-MK2-01.webp', '899.00', 5),
(82, 'VOID ELITE SURROUND', 'corsair', 'Auriculares premium para juegos VOID ELITE SURROUND con sonido envolvente 7.1, cherry.', 'Sumérjase en la acción con los CORSAIR VOID ELITE SURROUND, con transductores de audio de neodimio de 50 mm de ajuste personalizado, un cómodo tejido de rejilla de microfibra con almohadillas de espuma con memoria y un micrófono omnidireccional.', 'Recoge la voz con una claridad excepcional, mientras que una función de silenciado y un indicador LED de silenciado integrado le permiten saber cuándo le están oyendo y cuándo no.', 'Diseñados para garantizar la comodidad en largas sesiones de juego, con un tejido de rejilla de microfibra transpirable y lujosas almohadillas de espuma con memoria.', '1626770968_-CA-9011206-NA-Gallery-VOID-ELITE-SURROUND-RED-01.webp', '850.99', 10),
(83, 'HS70 PRO WIRELESS', 'corsair', 'Auriculares para juegos HS70 PRO WIRELESS, crema.', 'Los auriculares para juegos CORSAIR HS70 PRO WIRELESS son cómodos y de calidad, con almohadillas de espuma con memoria, transductores de audio de neodimio de 50 mm de ajuste personalizado y un modo inalámbrico de baja latencia de 2,4 GHz.', 'Los transductores de neodimio de 50 mm ajustados a medida y de alta calidad ofrecen el alcance suficiente para oír todo lo necesario en el campo de batalla. Sumérjase en un sonido envolvente 7.1, creando una experiencia de audio multicanal para que siempre esté en el medio de la acción.', 'Un micrófono unidireccional completamente extraíble reduce el ruido ambiente para que le escuchen alto y claro. Además, cuentan con el certificado Discord que garantiza una comunicación clara y el mejor sonido.', '1626770997_-CA-9011210-NA-Gallery-HS70-PRO-CREAM-01.webp', '800.00', 5),
(84, 'HS60 PRO SURROUND', 'corsair', 'Auriculares para juegos HS60 PRO SURROUND, carbón.', 'Los auriculares para juegos CORSAIR HS60 PRO SURROUND son cómodos y de calidad, con almohadillas de espuma con memoria, transductores de audio de neodimio de 50 mm de ajuste personalizado y un micrófono unidireccional extraíble con cancelación de ruido.', 'Los transductores de neodimio de 50 mm ajustados a medida y de alta calidad ofrecen el alcance suficiente para oír todo lo necesario en el campo de batalla. Sumérjase en un sonido envolvente 7.1, creando una experiencia de audio multicanal para que siempre esté en el medio de la acción.', 'Compatibilidad multiplataforma: PC, PS4, Xbox One*, Switch y dispositivos móviles a través de un conector chapado en oro de 3,5 mm. También puede conectar el 3,5 mm que se incluye a un adaptador USB para disfrutar del sonido envolvente 7.1 en PC.', '1626771029_-CA-9011213-NA-Gallery-HS60-PRO-CARBON-01.webp', '650.00', 10),
(85, 'HS50 PRO STEREO', 'corsair', 'Auriculares para juegos HS50 PRO STEREO, carbón.', 'Los auriculares para juegos CORSAIR HS50 PRO STEREO son cómodos y de calidad, con almohadillas de espuma con memoria, transductores de audio de neodimio de 50 mm de ajuste personalizado y un micrófono unidireccional extraíble con cancelación de ruido.', 'Los transductores de neodimio de 50 mm ajustados a medida y de alta calidad ofrecen el alcance suficiente para oír todo lo necesario en el campo de batalla.', 'Un micrófono unidireccional completamente extraíble reduce el ruido ambiente para que le escuchen alto y claro. Además, cuentan con el certificado Discord que garantiza una comunicación clara y el mejor sonido.', '1626771063_-CA-9011215-NA-Gallery-HS50-PRO-CARBON-01.webp', '500.00', 10),
(86, 'HS45 SURROUND', 'corsair', 'Auriculares para juegos HS45 SURROUND, Carbón.', 'Póngase los auriculares para juegos estéreo CORSAIR HS45 SURROUND y disfrute de una voz clara y de un sonido de gran calidad durante horas de juego gracias a la espuma viscoelástica y a las almohadillas ajustables, ideales para PC, PS4, Xbox One y mucho más.', 'Conecte el un adaptador USB incluido que ofrece un sonido envolvente 7.1 en PC, ofreciendo un audio multicanal inmersivo. Conecte y ajuste fácilmente los controles para volumen y silencio en el auricular sobre la marcha.', 'El micrófono unidireccional, extraíble y con la certificación Discord está optimizado para mejorar la calidad de la voz y reducir el ruido ambiente, de modo que puedan oírle alto y claro.', '1626771097_-CA-9011220-NA-Gallery-HS45-CARBON-01.webp', '488.00', 5),
(87, 'HS75 XB WIRELESS', 'corsair', 'Auriculares para juegos HS75 XB WIRELESS para Xbox One y Xbox Series X.', 'Los auriculares para juegos CORSAIR HS75 XB WIRELESS para Xbox Series X, Xbox Series S y Xbox One están equipados con un micrófono completamente extraíble, Dolby Atmos envolvente y conexión directa a la consola sin necesidad de adaptador inalámbrico.', 'Se conectan de forma inalámbrica sin adaptador a cualquier consola Xbox Series X, Series S o Xbox One para que el usuario disfrute de un audio de buena calidad y baja latencia.', 'Cambie fácilmente la atención sobre la acción con respecto a la conversación de sus compañeros de equipo, y viceversa, gracias a los controles de mezcla del audio del juego y el chat.', '1626771122_-base-hs75-xb-wireless-config-Gallery-HS75-XB-01.png_515Wx515H', '700.00', 10),
(88, 'HS60 HAPTIC', 'corsair', 'HS60 HAPTIC Stereo Gaming Headset with Haptic Bass.', 'Los auriculares para juegos CORSAIR HS60 HAPTIC ofrecen efectos hápticos en los bajos que se pueden sentir, con cómodas almohadillas de espuma viscoelástica y transductores de neodimio de 50 mm de ajuste personalizado para disfrutar de un audio de calidad.', 'Disfrute del juego como nunca antes con efectos hápticos en los bajos gracias a la Taction Technology. Sienta cada golpe, cada explosión, cada momento de tensión con un efecto de bajo táctil avanzado que le transporta al campo de batalla.', 'Con Taction Technology, los HS60 HAPTIC captan las frecuencias más bajas con mayor precisión que otros auriculares hápticos. La potente reproducción de bajos brinda a los auriculares un efecto de auténtico subwoofer en los bajos más profundos y en la respuesta a las bajas frecuencias.', '1626771168_-base-hs60-haptic-config-Gallery-HS60-Haptic-01.png_515Wx515H', '600.00', 10),
(89, 'HS70 BLUETOOTH', 'corsair', 'Auriculares con cable y Bluetooth para juegos HS70.', 'Los auriculares para juegos CORSAIR HS70 BLUETOOTH son cómodos y de calidad, con almohadillas de espuma con memoria, transductores de audio de neodimio de 50 mm de ajuste personalizado y una conexión simultánea por cable para el audio del juego y por Bluetooth para el chat.', 'Conéctelos por cable para disfrutar del audio del juego en Switch, PS5, PS4, Xbox Series X|S, Xbox One o PC y use el Bluetooth en su dispositivo móvil con aplicaciones de chat de voz, música o llamadas telefónicas al mismo tiempo.', 'Un micrófono unidireccional completamente extraíble reduce el ruido ambiente. Además, cuentan con el certificado Discord que garantiza una comunicación clara y una calidad de sonido sobresaliente.', '1626771202_-CA-9011227-NA-Gallery-HS70-Bluetooth-01.png_515Wx515H', '700.99', 5),
(90, 'HS70 WIRELESS', 'corsair', 'Auriculares para juegos HS70 WIRELESS, blanco.', 'Los auriculares para juegos CORSAIR HS70 Wireless ofrecen una comodidad excepcional, una calidad de sonido superior, un micrófono totalmente extraíble y hasta 16 horas de batería.', 'Los auriculares para juegos HS70 Wireless ofrecen una comodidad excepcional, una calidad de sonido superior, un micrófono totalmente extraíble y hasta 16 horas de batería. No pare de jugar con un alcance ampliado a 12 metros con baja latencia y una tecnología inalámbrica de 2,4 GHz.', 'El potente software CORSAIR iCUE permite personalizar los ajustes del ecualizador de sonido, controlar el ruido local y disfrutar de un sonido envolvente virtual e inmersivo.', '1626771259_-CA-9011177-AP-Gallery-HS-Series-01-HS70-WHT-300m.webp', '799.99', 10),
(91, 'HS60 SURROUND', 'corsair', 'Auriculares para juegos HS60 SURROUND, Carbón.', 'Los auriculares para juegos CORSAIR HS60 SURROUND ofrecen una comodidad excepcional y una calidad de sonido superior, y presentan resistentes materiales de fabricación metálicos para garantizar la durabilidad a largo plazo.', 'La lujosa espuma viscoelástica y las almohadillas ajustables proporcionan una comodidad excepcional. La legendaria calidad de fabricación de CORSAIR con resistentes materiales de fabricación metálicos garantiza la durabilidad a largo plazo', 'Los transductores del altavoz de neodimio de 50 mm especialmente ajustados ofrecen una calidad de sonido superior con un impresionante rango y precisión. El micrófono unidireccional optimizado reduce el ruido ambiental para mejorar la calidad de la voz y se puede desmontar con facilidad para su uso de viaje.', '1626771400_-CA-9011173-AP-Gallery-CA-9011173-AP-HS60-Carbon-01.webp', '650.99', 10),
(92, 'VIRTUOSO RGB Wireless XT', 'corsair', 'Auriculares para juegos de alta fidelidad VIRTUOSO RGB WIRELESS XT Slate.', 'Los CORSAIR VIRTUOSO RGB Wireless XT ofrecen una experiencia de sonido de alta fidelidad y una comodidad continua gracias a las orejeras de espuma viscoelástica premium y una conectividad simultánea con la rapidísima tecnología SLIPSTREAM WIRELESS y Bluetooth.', 'Baja latencia, tecnología inalámbrica de 2,4 GHz con hasta 18 m de alcance. La tecnología multipunto permite conectar hasta tres dispositivos inalámbricos SLIPSTREAM a un solo receptor.', 'El micrófono extraíble, de gran ancho de banda, omnidireccional y de 9,5 mm ofrece un amplio alcance dinámico y una calidad de voz magnífica con una excelente respuesta en el rango grave.', '1626771451_-CA-9011188-NA-Gallery-VIRTUOSO-XT-01.png_515Wx515H', '1000.99', 5),
(93, 'VOID ELITE STEREO', 'corsair', 'VOID ELITE STEREO Gaming Headset, Carbon.', 'Escuche toda la acción con CORSAIR VOID ELITE STEREO, que cuenta con controladores de audio de neodimio de 50 mm ajustados a medida, una cómoda tela de malla de microfibra con almohadillas de espuma viscoelástica y un micrófono omnidireccional.', 'Escuche en PC, PS4, Xbox One, Switch y dispositivos móviles a través de un conector universal de 3,5 mm y el cable Y-Splitter incluido.', 'La tela de malla de microfibra transpirable y las almohadillas de espuma viscoelástica de felpa te mantienen cómodo incluso durante largas sesiones de juego.', '1626771505_-CA-9011208-NA-Gallery-VOID-ELITE-STEREO-CARBON-01.png_515Wx515H', '999.99', 5),
(94, 'MM300', 'corsair', 'Alfombrilla para juegos de tela antidesgaste MM300.', 'La alfombrilla MM300 proporciona una superficie de tela resistente y suave con los bordes cosidos reforzados para evitar el desgaste. Su diseño entretejido se ha diseñado teniendo en cuenta los reflejos, permitiendo un control preciso del ratón, una precisión constante y una baja fricción.', 'Llévese la mejor equipación y juegue al máximo... MM300 está optimizada para ratones láser y ópticos para juegos. La base de caucho antideslizante la mantiene fija en su sitio.', 'La superficie textil está pensada para una precisión extrema y un rastreo de baja fricción, los bordes con costuras reforzadas evitan que la superficie se pele.', '1626771581_-CA-9011210-NA-Gallery-HS70-PRO-CREAM-01.webp', '350.99', 15),
(95, 'MM200', 'corsair', 'Alfombrilla para juegos de tela MM200.', 'La alfombrilla CORSAIR original, el modelo MM200, se ha diseñado para responder a cualquier estilo de juego y viene en distintos tamaños.', 'La edición compacta y perfecta para viajes es ligera y fácil de transportar. Independientemente de su tamaño, la alfombrilla MM200 puede responder a movimientos rápidos del ratón y, con su base antideslizamientos, no se moverá con la presión.', 'La alfombrilla CORSAIR original, el modelo MM200, se ha diseñado para responder a cualquier estilo de juego y viene en distintos tamaños. ¿Tienes una mesa grande? La edición XL la llenará. ¿Quieres jugar en cualquier parte?', '1626771608_-CH-9000099-WW-Gallery-MM200-001.webp', '299.00', 15),
(96, 'MM800 RGB POLARIS', 'corsair', 'Alfombrilla para juegos MM800 RGB POLARIS.', 'El modelo MM800 RGB POLARIS ofrece la resistencia, el seguimiento y la precisión de las alfombrillas CORSAIR, y añade un nuevo nivel de inmersión LED.', 'Combina una superficie de microtextura de fricción baja con una amplia área de acción para ofrecer un seguimiento preciso al píxel sin importar el estilo de juego. Sus 15 zonas RGB individuales incluyen la verdadera tecnología de iluminación PWM para representar el color con la mayor precisión.', 'Sincronice cada una de las zonas de iluminación con otros productos CORSAIR RGB gracias al software iCUE, y complete así la configuración definitiva para juegos.', '1626771651_-CH-9440020-NA-Gallery-MM800-01.webp', '499.00', 15),
(97, ' MM700 RGB', 'corsair', 'Alfombrilla extensa MM700 RGB.', 'La alfombrilla de tela extensa para juegos CORSAIR MM700 RGB proporciona una amplia superficie de 930 mm x 400 mm con amplio espacio para los periféricos, rodeada de la iluminación dinámica RGB de tres zonas y 360°.', 'Sumerja su área de juego en iluminación dinámica RGB de tres zonas y 360°. Alterne los 12 perfiles de iluminación RGB integrados con solo pulsar un botón, para una iluminación inmediata tan pronto como se conecte, o bien programe sus propios perfiles con el software CORSAIR iCUE.', 'Concentrador USB de dos puertos: Los puertos USB con una práctica ubicación proporcionan conexiones sencillas para periféricos adicionales, como un ratón o auriculares CORSAIR.', '1626771696_-base-mm700-rgb-config-Gallery-MM700-RGB-01.png_515Wx515H', '599.00', 15),
(98, 'MM350', 'corsair', 'Alfombrilla para juegos de tela antidesgaste premium MM350.', 'Disfrute de horas una comodidad de lujo en el juego con la alfombrilla para juegos de tela antidesgaste CORSAIR MM350 XL, con una amplia superficie de 450 x 400 mm con amplio espacio para ratones con sensores ópticos y sensores láser de alto rendimiento.', 'Haga grandes jugadas con un control superior gracias a la superficie textil tejida idónea para el deslizamiento y optimizada para ratones para juegos de alto rendimiento, con seguimiento de baja fricción que ofrece una precisión de píxeles.', 'Diseño duradero que resiste los juegos diarios con un borde antideslizamiento de 360° cosido con precisión que protege contra el desprendimiento de la superficie.', '1626771794_-CH-9413561-WW-Gallery-MM350-XL-01.webp', '400.00', 15),
(99, 'A50', 'astro', 'A50 AUDÍFONOS INALÁMBRICOS + ESTACIÓN BASE.', 'Disfruta del desempeño y el sonido de ASTRO Audio V2, y de la libertad sin cables. Los audífonos inalámbricos A50 + Estación base para Xbox/PC ofrecen la acústica, la ergonomía, el confort y la durabilidad premium que exigen jugadores y streamers. Disfruta de la más absoluta inmersión en audio con los audífonos inalámbricos ASTRO A50 + Estación base.', 'El software gratuito ASTRO Command Center ofrece a los jugadores un control total sobre su experiencia de audio, que incluye la comunicación verbal y la configuración de audio del juego. Disponible en Windows 10, XBox y Mac', ' Mostrar zona activa 1APTOS PARA MOD KITMostrar zona activa 2MICRÓFONO VOLTEABLE PARA SILENCIARMostrar zona activa 3OPTIMIZADOS CON ASTRO AUDIO V2Mostrar zona activa 4BATERÍA RECARGABLE DE ION LITIOMostrar zona activa 5APTOS PARA AUDIO 3DMostrar zona activa 6SOFTWARE ASTRO COMMAND CENTERMostrar zona activa 7FUNCIONALIDAD DE TARJETA DE SONIDO USBMostrar zona activa 8DOLBY AUDIOMostrar zona activa 9MIXAMP INTEGRADO  OPTIMIZADOS CON ASTRO AUDIO V2 ASTRO Audio V2 proporciona un espectro de frecuencias preciso y fluido para obtener imágenes acústicas detalladas y fieles a la realidad, así como la perfecta localización del sonido para disponer de una ventaja competitiva.', '1626772003_a50-gallery-ps4-01-refresh.webp', '1899.99', 5),
(100, 'A40 TR', 'astro', 'AUDÍFONOS A40 TR + MIXAMP PRO TR.', 'Los audífonos ASTRO A40 TR + MixAmp Pro TR son la solución de audio de gama alta para deportistas de eSports, creadores de contenido y asiduos del streaming. Cumplen los rigurosos requisitos de fidelidad de audio, confort y durabilidad que exigen los deportistas de eSports.', 'Configuración de audio profesional para jugadores. El software Astro Command Center (ACC) gratuito ofrece a los jugadores un mayor control sobre la comunicación de voz y la configuración de audio. Combinados con MixAmp Pro TR, los audífonos A40 TR ofrecen audio de calidad profesional, en casa o el escenario del torneo.', 'Los audífonos ASTRO están optimizados específicamente para juegos. Trabajamos en estrecha relación con desarrolladores, jugadores profesionales y streamers para ofrecer diálogo, música y sonidos de juego tal y como deben sonar. ASTRO Audio V2 proporciona un espectro de frecuencias neutro, fluido y ampliado para ofrecer audio detallado y realista.', '1626772053_a40-gen4-gallery-ps4-01-refresh.webp', '1499.99', 5),
(101, 'A10', 'astro', 'A10 AUDÍFONOS CON MICRÓFONO.', 'Los materiales premium, flexibles y ligeros eliminan la fatiga de los audífonos, mientras que el micrófono volteable para silenciar y el cable de chat compatible con Switch te mantienen al mando de tus comunicaciones. ¡Derrota a la Calamidad de Ganon, ayuda a la princesa Zelda y encuentra tu destino con un estilo legendario!', 'ASTRO Gaming te proporciona información y herramientas útiles para todos nuestros productos. Explora las secciones sobre los diferentes niveles de recursos como guías de inicio rápido y vídeos sobre configuración para todos los productos ASTRO Gaming.', 'Optimizados para juegos con la máxima precisión mediante ASTRO Audio, estos audífonos con micrófono llevan la profundidad de Hyrule a tu sala de estar con una fidelidad de audio insuperable con un puerto de audio de 3,5 mm.', '1626772116_a10-gallery-zelda-01.webp', '600.00', 10);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`id`, `email`, `password`) VALUES
(1, 'yostintejaxun@gmail.com', '$2y$10$4N/Cz/IbHUvHdrJ7uMLuhOGAwmXZomG9yzm.RCF84.zcNLqlEE.HS'),
(2, 'yostinacual18@hotmail.com', '$2y$10$cI1GmD6DmslNKPGdWNs9muuF4xxhdf/rONPRXb0/vA4TnaRniEQKq'),
(3, 'ejemplo@yahoo.com', '$2y$10$3liHKKGMgrM6Kc1Atb51peeM5n0mePEoWWIUNJC/a/uZze3ZXLX4a'),
(4, 'Yostin502@gmail.com', '$2y$10$.DLrE8U1Sk6Icxdhm8yEB.U2n1j4HY2TNLbJEq9zw4cr4q67QtMUm'),
(5, 'user21@gmail.com', '$2y$10$AgbJ/LznftjCo6MsusIvxuWN3WNjkOiYWZ2mbK3Vp9QhF.2tFXFZG'),
(6, 'juanito555a@hotmail.com', '$2y$10$2NNufc5h1hQpT9Ccj3PJWeIfoyGO30rqifloDvAUDSJckvZ/XGSRW'),
(8, 'selvin502@gmail.com', '$2y$10$DzNU4zFzlssB3swzwohxp.wdJjkIVccgtVTNoDUySYs8jusyH093O');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `productos`
--
ALTER TABLE `productos`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT de la tabla `productos`
--
ALTER TABLE `productos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=102;

--
-- AUTO_INCREMENT de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
